### ISSUE TITLE
images are not loaded correctly when using HTTP CONNECT in Chrome

### ISSUE THREAD

**Issue by jamesdbloom** [jamesdbloom/mockserver#107]
images are not loaded correctly when using HTTP CONNECT in Chrome which may be related to:

23:01:21.402 [nioEventLoopGroup-3-8] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x4ee03b5b, /192.168.1.102:65055 => /192.168.1.102:1090] Swallowing a harmless 'connection reset by peer / broken pipe' error that occurred while writing close_notify in response to the peer's close_notify
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_05]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_05]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_05]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_05]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:375) ~[na:1.8.0_05]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447) ~[netty-buffer-4.0.26.Final.jar:4.0.26.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[netty-buffer-4.0.26.Final.jar:4.0.26.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:241) ~[netty-transport-4.0.26.Final.jar:4.0.26.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) ~[netty-transport-4.0.26.Final.jar:4.0.26.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.26.Final.jar:4.0.26.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.26.Final.jar:4.0.26.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.26.Final.jar:4.0.26.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.26.Final.jar:4.0.26.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [netty-common-4.0.26.Final.jar:4.0.26.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.0.26.Final.jar:4.0.26.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]

**Comment by jamesdbloom** [comment]
fixed
