### ISSUE TITLE
Error parsing verify request between ruby client and mockserver-netty

### ISSUE THREAD

**Issue by jamesweakley** [jamesdbloom/mockserver#166]
Hi - great framework! but I have encountered an issue.

I have mockserver-netty-3.9.17-jar-with-dependencies.jar running on a linux server on port 8086.

Using mockserver-client 1.0.7.pre in ruby (and I have also tried several older versions), and for the purposes of reporting the issue I am trying to perform the sample request shown at: https://github.com/jamesdbloom/mockserver/tree/master/mockserver-client-ruby#ruby-2

I will attach the error I'm getting from ruby on the client side, a screenshot of the output http request (captured with Microsoft Network Monitor) and the error I'm seeing on the server side.

I have also noticed that when I perform the same request using the node.js client, it makes a request to /verify with a JSON body as opposed to the ruby client which hits /retrieve with a www-form-urlencoded body

![http_payload_outbound](https://cloud.githubusercontent.com/assets/2681392/9460655/9ff9a5a2-4b4b-11e5-801d-6ea23ce6c595.png)

**Comment by jamesweakley** [comment]
Client Error: 
RestClient::BadRequest: 400 Bad Request
        from C:/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rest-client-1.7.2/lib/restclient/abstract_response.rb:48:in `return!'
        from C:/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rest-client-1.7.2/lib/restclient/request.rb:495:in `process_result'
        from C:/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rest-client-1.7.2/lib/restclient/request.rb:421:in `block in transmit'
        from C:/jruby-9.0.0.0/lib/ruby/stdlib/net/http.rb:857:in `start'
        from C:/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rest-client-1.7.2/lib/restclient/request.rb:413:in `transmit'
        from C:/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rest-client-1.7.2/lib/restclient/request.rb:176:in `execute'
        from C:/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rest-client-1.7.2/lib/restclient/request.rb:41:in `execute'
        from C:/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rest-client-1.7.2/lib/restclient/resource.rb:80:in `put'
        from C:/jruby-9.0.0.0/lib/ruby/gems/shared/gems/mockserver-client-1.0.7.pre/lib/mockserver/abstract_client.rb:69:in `retrieve'
        from C:/jruby-9.0.0.0/lib/ruby/gems/shared/gems/mockserver-client-1.0.7.pre/lib/mockserver/abstract_client.rb:100:in `verify'
        from (irb):21:in `<eval>'

**Comment by jamesweakley** [comment]
Server error:

2015-08-25 16:55:44,267 ERROR o.m.m.MockServerHandler Exception processing {
  "method" : "PUT",
  "path" : "/retrieve",
  "headers" : [ {
    "name" : "Accept",
    "values" : [ "*/*; q=0.5, application/xml" ]
  }, {
    "name" : "Accept-Encoding",
    "values" : [ "gzip, deflate" ]
  }, {
    "name" : "Content-Length",
    "values" : [ "168" ]
  }, {
    "name" : "User-Agent",
    "values" : [ "Ruby" ]
  }, {
    "name" : "Host",
    "values" : [ "server:8086" ]
  }, {
    "name" : "Content-Type",
    "values" : [ "application/x-www-form-urlencoded" ]
  } ],
  "keepAlive" : true,
  "secure" : false,
  "body" : {
    "type" : "BINARY",
    "value" : "eyJodHRwUmVxdWVzdCI6eyJtZXRob2QiOiJQT1NUIiwicGF0aCI6Ii9sb2dpbiIsImNvb2tpZXMiOlt7InZhbHVlcyI6WyIuKiJdLCJuYW1lIjoic2Vzc2lvbklkIn1dLCJib2R5Ijp7InR5cGUiOiJTVFJJTkciLCJ2YWx1ZSI6Int1c2VybmFtZTogJ2ZvbycsIHBhc3N3b3JkOiAnYmFyJ30ifX19"
  }
}
java.lang.RuntimeException: Exception while parsing response [eyJodHRwUmVxdWVzdCI6eyJtZXRob2QiOiJQT1NUIiwicGF0aCI6Ii9sb2dpbiIsImNvb2tpZXMiOlt7InZhbHVlcyI6WyIuKiJdLCJuYW1lIjoic2Vzc2lvbklkIn1dLCJib2R5Ijp7InR5cGUiOiJTVFJJTkciLCJ2YWx1ZSI6Int1c2VybmFtZTogJ2ZvbycsIHBhc3N3b3JkOiAnYmFyJ30ifX19] for http response httpRequest
        at org.mockserver.client.serialization.HttpRequestSerializer.deserialize(HttpRequestSerializer.java:48) ~[mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at org.mockserver.mockserver.MockServerHandler.channelRead0(MockServerHandler.java:101) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at org.mockserver.mockserver.MockServerHandler.channelRead0(MockServerHandler.java:40) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at org.mockserver.server.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:101) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at org.mockserver.server.unification.PortUnificationHandler.channelRead0(PortUnificationHandler.java:41) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at org.mockserver.server.unification.PortUnificationHandler.channelRead0(PortUnificationHandler.java:21) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'eyJodHRwUmVxdWVzdCI6eyJtZXRob2QiOiJQT1NUIiwicGF0aCI6Ii9sb2dpbiIsImNvb2tpZXMiOlt7InZhbHVlcyI6WyIuKiJdLCJuYW1lIjoic2Vzc2lvbklkIn1dLCJib2R5Ijp7InR5cGUiOiJTVFJJTkciLCJ2YWx1ZSI6Int1c2VybmFtZTogJ2ZvbycsIHBhc3N3b3JkOiAnYmFyJ30ifX19': was expecting ('true', 'false' or 'null')
 at [Source: eyJodHRwUmVxdWVzdCI6eyJtZXRob2QiOiJQT1NUIiwicGF0aCI6Ii9sb2dpbiIsImNvb2tpZXMiOlt7InZhbHVlcyI6WyIuKiJdLCJuYW1lIjoic2Vzc2lvbklkIn1dLCJib2R5Ijp7InR5cGUiOiJTVFJJTkciLCJ2YWx1ZSI6Int1c2VybmFtZTogJ2ZvbycsIHBhc3N3b3JkOiAnYmFyJ30ifX19; line: 1, column: 449]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487) ~[mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518) ~[mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2299) ~[mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1458) ~[mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683) ~[mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3602) ~[mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3547) ~[mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578) ~[mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        at org.mockserver.client.serialization.HttpRequestSerializer.deserialize(HttpRequestSerializer.java:36) ~[mockserver-netty-3.9.17-jar-with-dependencies.jar:na]
        ... 34 common frames omitted

**Comment by jamesdbloom** [comment]
Sorry I've been away for a couple of weeks, I'll take a look at this in the next few days.

**Comment by jamesweakley** [comment]
No worries James, thanks heaps for looking at it.

**Comment by schechi1190** [comment]
Hi James, Thanks for this awesome tool. I am also having same issue as jamesweakley. I need to retrieve requests from the server. All options (retrieve, dumpToLog etc..) are throwing same exception

**Comment by jamesdbloom** [comment]
Closing as this issue will be fixed once the ruby client is re-written, that will happen once support for generating clients from Open API 3.0 becomes available https://github.com/swagger-api/swagger-codegen. Closing this issue as related to #182.
