### ISSUE TITLE
https request - getting certificate_unknown

### ISSUE THREAD

**Issue by morphysk** [jamesdbloom/mockserver#185]
Hello,

I want to mock the server for my mobile application. Currently I stacked on ssl certificate. Can you please provide exact steps how I can get ssl certificate used by mock-server for ssl communication and use it on mobile?
Adding log from mockserver
Thank you for your help.

Ivan

<code>
java -Dfile.encoding=UTF-8 -Dmockserver.logLevel=INFO -Dlog.dir=/usr/local/var/log/mockserver/ -jar /usr/local/lib/mockserver/mockserver-netty-jar-with-dependencies.jar  -serverPort 1080
2015-10-01 15:56:26,339 INFO o.m.m.MockServer MockServer started on port: 1080
2015-10-01 15:57:03,701 WARN i.n.c.DefaultChannelPipeline An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:358) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [mockserver-netty-jar-with-dependencies.jar:na]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
Caused by: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[na:1.7.0_51]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1619) ~[na:1.7.0_51]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1587) ~[na:1.7.0_51]
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1756) ~[na:1.7.0_51]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1060) ~[na:1.7.0_51]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:884) ~[na:1.7.0_51]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:758) ~[na:1.7.0_51]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.7.0_51]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1155) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1019) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:959) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327) ~[mockserver-netty-jar-with-dependencies.jar:na]
	... 12 common frames omitted
</code>

**Comment by jamesdbloom** [comment]
How are you running MockServer?

**Comment by morphysk** [comment]
I tried to run it as standalone java jar and also tried to install mockserver from brew repository: mockserver -serverPort 1080

**Comment by jamesdbloom** [comment]
What operating system and version of java are you using as I can't seem to reproduce this error.

**Comment by morphysk** [comment]
I am running MacOS 10.10.5, jdk 1.8, tried mockserver-netty-3.9.17-jar-with-dependencies.jar 
App is running on android6
Thanks for your help

**Comment by morphysk** [comment]
I identified the problem - android dont trust ssl certificate of mockserver. Is there any way how I can specify ssl cert which should be used by mock server? Thanks.

**Comment by jamesdbloom** [comment]
Unfortunately that would never be possible otherwise that would break SSL as it would allow anyone (MockServer is this case) to pretend to be someone else by using their SSL certificate.  

If ensure Android recognises the certificate you will need to add the MockServer CA certificate to the Android truststore.  

There is a script [here](https://github.com/jamesdbloom/mockserver/blob/master/scripts/install_ca_certificate.sh) that shows you how to do this for a JVM on a mac or linux machine.  

You could also check out blogs on how to do this for Android: 
* http://wiki.cacert.org/FAQ/ImportRootCert#Android_Phones_.26_Tablets
* http://stackoverflow.com/questions/4461360/how-to-install-trusted-ca-certificate-on-android-device
* http://nelenkov.blogspot.co.uk/2011/12/using-custom-certificate-trust-store-on.html

**Comment by unludo** [comment]
Hi,
I think it would be useful in the doc for android users.
Ludovic

**Comment by jamesdbloom** [comment]
I'm very happy to extend the documentation for android users.  Perhaps you could provide me with the steps then I test it and add it to the documentation.
