### ISSUE TITLE
https requests failing with: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown

### ISSUE THREAD

**Issue by schwarzmann** [jamesdbloom/mockserver#205]
Hi,

Just trying to run the proxy, and while http works, https is not.  I'm seeing the following stacktrace on both Mac OS (El Capitan) with java 1.8.0_60 and also on Ubuntu 14.04.2 LTS with java 1.8.0_45.  I've tried both the latest distribution and also building code base and I have run the install_ca_certificate.sh script.  Perhaps I missed a setup or configuration step?

Thanks,
-Bob.

$ java -Dmockserver.logLevel=INFO -jar ~/Downloads/mockserver-netty-3.10.1-jar-with-dependencies.jar -serverPort 1080 -proxyPort 1090
2015-12-07 10:10:49,989 INFO o.m.m.MockServer MockServer started on port: 1080
2015-12-07 10:10:49,993 INFO o.m.p.http.HttpProxy MockServer proxy started on port: 1090
2015-12-07 10:10:55,934 WARN o.m.p.r.RelayConnectHandler Exception caught by upstream relay handler -> closing pipeline [id: 0x5fad7478, /0:0:0:0:0:0:0:1:56214 :> 0.0.0.0/0.0.0.0:1090]
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:358) ~[mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230) ~[mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[na:1.8.0_60]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[na:1.8.0_60]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[na:1.8.0_60]
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[na:1.8.0_60]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[na:1.8.0_60]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[na:1.8.0_60]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_60]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_60]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1135) ~[mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1025) ~[mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:965) ~[mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327) ~[mockserver-netty-3.10.1-jar-with-dependencies.jar:na]
	... 12 common frames omitted

**Comment by schwarzmann** [comment]
Looks like trusting the CA certificate (CertificateAuthorityCertificate.pem) at the OS level has helped.  Firefox doesn't seem to be happy with the cert.

Maybe this can be added to the documentation?  I didn't see any notes on vending the certificate from mock-server-proxy but that would ease getting the cert distributed.

**Comment by fpoyer** [comment]
I've had pretty much the same problem : trying to run the Proxy (without the server) in order to record interaction between my application and a remote server, over secure web (http**s**) to latter be able to set the Server to replay these interactions while offline (setting up Unit test for legacy code).

I wasn't able to add the CA certificate at OS level though, since that would have meant the tests would fail on any machine but mine, so I had to find a way to do it in code. Here is the solution I've found:

```java
import javax.net.ssl.HttpsURLConnection;

import org.mockserver.socket.SSLFactory;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import org.apache.xmlrpc.client.XmlRpcClient;
import org.apache.xmlrpc.client.XmlRpcClientConfigImpl;
import org.apache.xmlrpc.client.XmlRpcSun15HttpTransportFactory;
import org.apache.xmlrpc.client.XmlRpcTransportFactory;

public class TestClass {

	@BeforeClass
	public static void startProxyAndServer() throws Exception {
		HttpsURLConnection.setDefaultSSLSocketFactory(SSLFactory.getInstance().sslContext().getSocketFactory());
		proxy = ClientAndProxy.startClientAndProxy(PortFactory.findFreePort());
	}

	@AfterClass
	public static void stopServerAndProxy() {
		proxy.dumpToLogAsJava();
		proxy.stop();
	}

	@Test
	public void should_test_something() throws Exception {
		// Write your code calling your server here, not forgetting to
		// **set up your client to use the proxy**
		// In my case, using Apache's XML-RPC client library, I had to do the following:

		XmlRpcClient client = new XmlRpcClient();
		XmlRpcTransportFactory factory = client.getTransportFactory();
		if (factory != null && factory instanceof XmlRpcSun15HttpTransportFactory) {
			String proxyHost = System.getProperty("https.proxyHost");
			if (proxyHost == null || proxyHost.isEmpty()) {
				proxyHost = System.getProperty("http.proxyHost");
			}
			String proxyPortString = System.getProperty("https.proxyPort");
			if (proxyPortString == null || proxyPortString.isEmpty()) {
				proxyPortString = System.getProperty("http.proxyPort");
			}

			if (proxyHost != null && !proxyHost.isEmpty()) {
				int proxyPort = 443;
				if (proxyPortString != null && !proxyPortString.isEmpty()) {
					try {
						proxyPort = Integer.parseInt(proxyPortString);
					} catch (NumberFormatException e) {
						// Port badly defined, keep the default
					}
				}
				Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort));
				((XmlRpcSun15HttpTransportFactory) factory).setProxy(proxy);
			}
		} else {
			System.err.println("No transport factory or not compatible with Proxy support!");
		}
```

**Comment by jamesdbloom** [comment]
Thanks this is very useful input I will definitely add this into the documentation.

**Comment by jamesdbloom** [comment]
The key line here is:

```java
HttpsURLConnection.setDefaultSSLSocketFactory(SSLFactory.getInstance().sslContext().getSocketFactory());
```

This will work for any direct use of the JDK API for HTTP or any library that depends on it .

My existing documentation only covers how to configure the proxy settings but not how to add the root certificate.

**Comment by fpoyer** [comment]
Glad I could help a good product! :)

**Comment by jamesdbloom** [comment]
Closing as this point was added to the documentation issue

**Comment by astupka** [comment]
This saved me a lot of headache! Thank you!  I couldn't find this mentioned in the documentation on http://mock-server.com/

**Comment by TheMover** [comment]
@jamesdbloom Is there an equivalent class to `SSLFactory` in version 5+? I found `SSLContextFactory` but there are no methods that produce a `javax.net.ssl.SSLSocketFactory` which is what `HttpsURLConnection.setDefaultSSLSocketFactory` needs.

**Comment by delcio19** [comment]
I've been struggling for a complete day trying to make a simple test using MockServer 5.5.0 and finally this line made the trick:

```java
HttpsURLConnection.setDefaultSSLSocketFactory(
    KeyStoreFactory.keyStoreFactory().sslContext().getSocketFactory()
);
```

I'm adding a simple test example using JUnit 5 API and MockServer 5.5.0 just for completness sake because I couldn't find any in the [documentation](http://www.mock-server.com/).



```java
package com.https.test;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.mockserver.configuration.ConfigurationProperties;
import org.mockserver.integration.ClientAndServer;
import org.mockserver.model.HttpRequest;
import org.mockserver.model.HttpResponse;
import org.mockserver.socket.KeyStoreFactory;    
import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.SSLSocketFactory;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.ByteBuffer;
import java.nio.channels.Channels;
import java.nio.channels.ReadableByteChannel;
import java.nio.charset.StandardCharsets;

public class HttpsMockServerTests {

    private static SSLSocketFactory defaultSocketFactory;
    private static ClientAndServer mockServer;

    @BeforeAll
    static void setupAll() {
        ConfigurationProperties.deleteGeneratedKeyStoreOnExit(true);
        mockServer = ClientAndServer.startClientAndServer(1090);
        /*
         * Backup DefaultSSLConnectionFactory and set MockServer SSLConnectionFactory
         */
        defaultSocketFactory = HttpsURLConnection.getDefaultSSLSocketFactory();
        HttpsURLConnection.setDefaultSSLSocketFactory(
            KeyStoreFactory.keyStoreFactory().sslContext().getSocketFactory()
        );
    }

    @AfterAll
    static void cleanupAll() {
        mockServer.stop();
        /*
         * Restore DefaultSSLConnectionFactory
         */
        HttpsURLConnection.setDefaultSSLSocketFactory(defaultSocketFactory);
    }

    @Test
    void testingHttpsCall() throws IOException {
        // given:
        int expectedStatus = 200;
        String expectedMessage = "Hello from secure endpoint!";
        String endpoint = String.format("https://localhost:%d/endpoint/test", mockServer.getLocalPort());

        mockServer
            .when(
                HttpRequest.request()
                    .withSecure(true)
                    .withMethod("GET")
                    .withPath("/endpoint/test")
            ).respond(
                HttpResponse.response()
                    .withStatusCode(expectedStatus)
                    .withHeader("Content-Type", "text/plain")
                    .withBody(expectedMessage)
            );

        // when:
        URL url = new URL(endpoint);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();

        int bufferSize = 1024;
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream(bufferSize);
        ReadableByteChannel readChannel = Channels.newChannel(connection.getInputStream());
        ByteBuffer buffer = ByteBuffer.allocate(bufferSize);

        while (readChannel.read(buffer) != -1) {
            outputStream.write(buffer.array(), 0, buffer.position());
            buffer.rewind();
        }
        String message = new String(outputStream.toByteArray(), StandardCharsets.UTF_8);

        // then:
        Assertions.assertEquals(expectedStatus, connection.getResponseCode());
        Assertions.assertEquals(expectedMessage, message);

        // cleanup:
        readChannel.close();
        outputStream.close();
    }
}
```

**Comment by jflefebvre06** [comment]
Hello,

Running this code I get a  `javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty` (I'm using open JDK 11.3)

**Comment by zippolyte** [comment]
Got the same issue as @jflefebvre06, and found a workaround. See #744
