### ISSUE TITLE
https request failing with "javax.net.ssl.SSLException: Received fatal alert: bad_certificate"

### ISSUE THREAD

**Issue by RobQuads** [jamesdbloom/mockserver#212]
I am trying to run MockServer in a WebProxy mode, I started it with the following parameters:

sudo java -Djavax.net.ssl.trustStore=/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/security/cacerts -Dmockserver.logLevel=TRACE -jar ./mockserver-jetty-jar-with-dependencies.jar -proxyPort 553 

This is running on a MacOS machine running 10.11.3 & Java 1.8.0_66

When we try and log into the endpoint (https://login.salesforce.com) we see the following error. 

2016-01-27 20:32:20,239 WARN o.m.p.r.RelayConnectHandler Exception caught by upstream relay handler -> closing pipeline [id: 0xad007805, /9.20.242.65:58251 => /9.20.242.65:553]
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: bad_certificate
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:358) ~[mockserver-jetty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230) ~[mockserver-jetty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [mockserver-jetty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [mockserver-jetty-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [mockserver-jetty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [mockserver-jetty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [mockserver-jetty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [mockserver-jetty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [mockserver-jetty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [mockserver-jetty-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [mockserver-jetty-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [mockserver-jetty-jar-with-dependencies.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
Caused by: javax.net.ssl.SSLException: Received fatal alert: bad_certificate
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[na:1.8.0_66]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[na:1.8.0_66]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[na:1.8.0_66]
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[na:1.8.0_66]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[na:1.8.0_66]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[na:1.8.0_66]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_66]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_66]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1135) ~[mockserver-jetty-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1025) ~[mockserver-jetty-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:965) ~[mockserver-jetty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327) ~[mockserver-jetty-jar-with-dependencies.jar:na]
	... 12 common frames omitted

In the browser we see

"An error occurred during a connection to eu6.salesforce.com. security library: improperly formatted DER-encoded message. (Error code: sec_error_bad_der) "

As far as we are aware we have all the CA certificates imported into the java keystone of the endpoint site. 

Any ideas what would cause this? or how to get extra information to work out what we need to import to get it working?

**Comment by jamesdbloom** [comment]
It looks like you are using `mockserver-jetty-jar-with-dependencies`.  The latest version of this is 2.9 however the current version of the MockServer is 3.10.2.  I suspect if you switched to using `mockserver-netty-jar-with-dependencies` then this problem would be already fixed.  I'm going to close this ticket, but if you stil see the problem with `mockserver-netty-jar-with-dependencies` version 3.10.2 please re-open it.
