### ISSUE TITLE
Proposal: Template syntax for responses

### ISSUE THREAD

**Issue by drslump** [jamesdbloom/mockserver#240]
The scenario I would like to discuss a solution for is to provide a simple mechanism for defining a dynamic response without having to write a custom callback or rely on the websocket RPC idea from #160.

The gist of it would be to have a new *response action* called `template` that would collect all the request parameters (including parsed bodies) and apply them to the provided response using a template engine. For instance with FreeMarker that I saw it's already used in the project?

This approach should provide a friction-free solution to users without Java mastery to solve some common use cases like including a request parameter in the response. Although by glancing at the capabilities of FreeMarker's template syntax it might even solve much more complex scenarios with some imagination.

To be honest, I was designing [my own HTTP mock server](https://gist.github.com/drslump/17d7d4f80ab8996d36a03665244eef18) before I stumbled upon this project, it looks like it covers all my expectations bar the templating thing. While this could most probably be implemented with the current callbacks mechanism, I lack the Java knowledge to do it myself without investing some big chunk of time on it, time I could invest in writing a Python client for `mockserver` :)

**Comment by jamesdbloom** [comment]
I agree this is a good idea, once I have finished updating the documentation I will implement a solution for this.

**Comment by jamesdbloom** [comment]
I am currently working on this now as there is a solid block of time scheduled in two weeks to update the documentation.  I have implemented most of the logic except for some further test coverage.  For a quick example of what is implemented (in the current SNAPSHOT):

*JavaScript templates*

```java
ClientAndServer.startClientAndServer(1080)
        .when(
                request()
                        .withPath(calculatePath("some_path"))
        )
        .respond(
                template(
                        HttpTemplate.TemplateType.JAVASCRIPT,
                        "return {" + NEW_LINE +
                                "     'statusCode': 200," + NEW_LINE +
                                "     'cookies': request.cookies," +
                                "     'body': JSON.stringify(" + NEW_LINE +
                                "               {" + NEW_LINE +
                                "                    method: request.method," +
                                "                    path: request.path," +
                                "                    body: request.body" +
                                "               }" + NEW_LINE +
                                "          )" + NEW_LINE +
                                "};" + NEW_LINE
                )
        );
```

*Velocity templates*

```java
ClientAndServer.startClientAndServer(1080)
        .when(
                request()
                        .withPath(calculatePath("some_path"))
        )
        .respond(
                template(
                        HttpTemplate.TemplateType.VELOCITY,
                        "{" + NEW_LINE +
                                "     \"statusCode\": 200," + NEW_LINE +
                                "     \"headers\": $!request.headers," + NEW_LINE +
                                "     \"cookies\": $!request.cookies," + NEW_LINE +
                                "     \"body\": \"$!request.body\"" + NEW_LINE +
                                "}" + NEW_LINE
                )
                .withDelay(TimeUnit.SECONDS, 5)
        );
```

When I update the documentation shortly I will add extensive documentation of how to use this feature and what the limitations / debugging approaches are.

**Comment by IamEmraan** [comment]
Hi james,
We are trying to use Javascript Template for Dynamic response, but it is not working, looks like it is broken.

**Here is the REST request I am using to set expectation:**

PUT http://localhost:1080/expectation
PUT data:
{
    "httpRequest": {
        "path": "/test12345"
    },
    "httpResponseTemplate": {
        "template": "return {\n" +
        "     'statusCode': 200,\n" +
        "     'cookies': {\n" +
        "          'session' : request.headers['Session-Id'][0]\n" +
        "     },\n" +
        "     'headers': {\n" +
        "          'Date' : Date()\n" +
        "     },\n" +
        "     'body': JSON.stringify(\n" +
        "               {\n" +
        "                    method: request.method," +
        "                    path: request.path," +
        "                    body: request.body" +
        "               }\n" +
        "          )\n" +
        "};",
        "templateType": "JAVASCRIPT"
    }
}


 

[no cookies]

Request Headers:
Connection: close
Content-Length: 757
Content-Type: text/plain; charset=ISO-8859-1
Host: localhost:1080
User-Agent: Apache-HttpClient/4.5.5 (Java/10.0.1)


**-->>And this the response we get when we are trying to run this expectation**

com.fasterxml.jackson.core.JsonParseException: Unexpected character ('+' (code 43)): was expecting comma to separate Object entries
 at [Source: (String)"{
    "httpRequest": {
        "path": "/test12345"
    },
    "httpResponseTemplate": {
        "template": "return {\n" +
        "     'statusCode': 200,\n" +
        "     'cookies': {\n" +
        "          'session' : request.headers['Session-Id'][0]\n" +
        "     },\n" +
        "     'headers': {\n" +
        "          'Date' : Date()\n" +
        "     },\n" +
        "     'body': JSON.stringify(\n" +
        "               {\n" +
        "                    met"[truncated 257 chars]; line: 6, column: 35]

could you please help us to resolve this issue, as we have tried everything possible.

**Mock Server Console Log:**
Note: Mock Server started from command line using executable jar: mockserver-netty-5.3.0-jar-with-dependencies.jar

D:\MockServer>java -Dmockserver.logLevel=INFO -jar mockserver-netty-5.3.0-jar-with-dependencies.jar -serverPort 1080
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/D:/MockServer/mockserver-netty-5.3.0-jar-with-dependencies.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-06-25 15:59:18,481 INFO o.m.m.MockServer MockServer started on port: 1080
2018-06-25 15:59:27,852 ERROR o.m.m.HttpStateHandler Exception processing {
  "method" : "PUT",
  "path" : "/expectation",
  "headers" : {
    "Connection" : [ "close" ],
    "Content-Length" : [ "757" ],
    "Content-Type" : [ "text/plain; charset=ISO-8859-1" ],
    "Host" : [ "localhost:1080" ],
    "User-Agent" : [ "Apache-HttpClient/4.5.5 (Java/10.0.1)" ]
  },
  "keepAlive" : false,
  "secure" : false,
  "body" : "{\r\n    \"httpRequest\": {\r\n        \"path\": \"/test12345\"\r\n    },\r\n    \"httpResponseTemplate\": {\r\n        \"template\": \"return {\\n\" +\r\n        \"     'statusCode': 200,\\n\" +\r\n        \"     'cookies': {\\n\" +\r\n        \"          'session' : request.headers['Session-Id'][0]\\n\" +\r\n        \"     },\\n\" +\r\n        \"     'headers': {\\n\" +\r\n        \"          'Date' : Date()\\n\" +\r\n        \"     },\\n\" +\r\n        \"     'body': JSON.stringify(\\n\" +\r\n        \"               {\\n\" +\r\n        \"                    method: request.method,\" +\r\n        \"                    path: request.path,\" +\r\n        \"                    body: request.body\" +\r\n        \"               }\\n\" +\r\n        \"          )\\n\" +\r\n        \"};\",\r\n        \"templateType\": \"JAVASCRIPT\"\r\n    }\r\n}\r\n\r\n\r\n "
}
java.lang.IllegalArgumentException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('+' (code 43)): was expecting comma to separate Object entries
 at [Source: (String)"{
    "httpRequest": {
        "path": "/test12345"
    },
    "httpResponseTemplate": {
        "template": "return {\n" +
        "     'statusCode': 200,\n" +
        "     'cookies': {\n" +
        "          'session' : request.headers['Session-Id'][0]\n" +
        "     },\n" +
        "     'headers': {\n" +
        "          'Date' : Date()\n" +
        "     },\n" +
        "     'body': JSON.stringify(\n" +
        "               {\n" +
        "                    met"[truncated 257 chars]; line: 6, column: 35]
        at org.mockserver.client.serialization.JsonArraySerializer.returnJSONObjects(JsonArraySerializer.java:30) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at org.mockserver.client.serialization.ExpectationSerializer.deserializeArray(ExpectationSerializer.java:94) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at org.mockserver.mock.HttpStateHandler.handle(HttpStateHandler.java:218) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at org.mockserver.mockserver.MockServerHandler.channelRead0(MockServerHandler.java:64) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at org.mockserver.mockserver.MockServerHandler.channelRead0(MockServerHandler.java:37) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at org.mockserver.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:188) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at org.mockserver.unification.PortUnificationHandler.channelRead0(PortUnificationHandler.java:91) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at org.mockserver.unification.PortUnificationHandler.channelRead0(PortUnificationHandler.java:37) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at java.base/java.lang.Thread.run(Unknown Source) [na:na]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('+' (code 43)): was expecting comma to separate Object entries
 at [Source: (String)"{
    "httpRequest": {
        "path": "/test12345"
    },
    "httpResponseTemplate": {
        "template": "return {\n" +
        "     'statusCode': 200,\n" +
        "     'cookies': {\n" +
        "          'session' : request.headers['Session-Id'][0]\n" +
        "     },\n" +
        "     'headers': {\n" +
        "          'Date' : Date()\n" +
        "     },\n" +
        "     'body': JSON.stringify(\n" +
        "               {\n" +
        "                    met"[truncated 257 chars]; line: 6, column: 35]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1798) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:561) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2271) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:892) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:247) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:255) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4044) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2539) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at org.mockserver.client.serialization.JsonArraySerializer.returnJSONObjects(JsonArraySerializer.java:21) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        ... 52 common frames omitted
2018-06-25 15:59:28,013 INFO o.m.m.HttpStateHandler no active expectations when receiving request:

        {
          "method" : "GET",
          "path" : "/test12345",
          "headers" : {
            "content-length" : [ "0" ],
            "Connection" : [ "close" ],
            "User-Agent" : [ "Apache-HttpClient/4.5.5 (Java/10.0.1)" ],
            "Host" : [ "localhost:1080" ]
          },
          "keepAlive" : false,
          "secure" : false
        }

2018-06-25 15:59:28,020 INFO o.m.m.HttpStateHandler no matching expectation - returning:

        {
          "statusCode" : 404,
          "reasonPhrase" : "Not Found"
        }

 for request:

        {
          "method" : "GET",
          "path" : "/test12345",
          "headers" : {
            "content-length" : [ "0" ],
            "Connection" : [ "close" ],
            "User-Agent" : [ "Apache-HttpClient/4.5.5 (Java/10.0.1)" ],
            "Host" : [ "localhost:1080" ]
          },
          "keepAlive" : false,
          "secure" : false
        }

Thanks,
syed
