### ISSUE TITLE
java.lang.NoClassDefFoundError: io/netty/channel/AbstractChannel$AbstractUnsafe$7

### ISSUE THREAD

**Issue by straumat** [jamesdbloom/mockserver#243]
Hi everyone.

I'm using the "mockserver-maven-plugin" (3.10.4) and I implemented a class extending "ExpectationInitializer".

Everything works fine with this sample code : 
`File folder = new File("data_blocks/");
File[] listOfFiles = folder.listFiles();`

But when I add : `int i = listOfFiles.length;` i get random exceptions when running maven like this one : 

` [WARNING] Unexpected exception in the selector loop.
java.lang.NoClassDefFoundError: io/netty/channel/AbstractChannel$AbstractUnsafe$7
	at io.netty.channel.AbstractChannel$AbstractUnsafe.deregister(AbstractChannel.java:657)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.fireChannelInactiveAndDeregister(AbstractChannel.java:621)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:604)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:534)
	at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:361)Exception in thread "nioEventLoopGroup-2-2" 
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.netty.util.concurrent.DefaultPromise$2
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 5 more
Exception in thread "nioEventLoopGroup-2-5" 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
Exception in thread "nioEventLoopGroup-2-6" 	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:590)Caused by: java.lang.ClassNotFoundException: io.netty.channel.AbstractChannel$AbstractUnsafe$7

	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:398)	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)

	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)

	at java.lang.Thread.run(Thread.java:745)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 9 more`
Here is my pom : 
`	
	<dependencies>

		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jetty</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
		    <groupId>org.hsqldb</groupId>
		    <artifactId>hsqldb</artifactId>
		    <scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>9.4.1208</version>
		</dependency>

	</dependencies>

	
	<build>
		<plugins>

			
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-checkstyle-plugin</artifactId>
				<version>2.8</version>
				<executions>
					<execution>
						<phase>process-sources</phase>
						<goals>
							<goal>check</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<consoleOutput>true</consoleOutput>
					<configLocation>${project.basedir}/checkstyle_configuration.xml</configLocation>
					<failOnViolation>true</failOnViolation>
					<violationSeverity>warning</violationSeverity>
				</configuration>
			</plugin>

			
			<plugin>
			    <groupId>org.mock-server</groupId>
			    <artifactId>mockserver-maven-plugin</artifactId>
			    <version>3.10.4</version>
			    <configuration>
			        <serverPort>8332</serverPort>
			        <proxyPort>1090</proxyPort>
			        <logLevel>DEBUG</logLevel>
			        <initializationClass>com.oakinvest.bfb.util.BitcoindMockServer</initializationClass>
			    </configuration>
			    <executions>
			        <execution>
			            <id>validate</id>
			            <phase>validate</phase>
			            <goals>
			                <goal>start</goal>
			            </goals>
			        </execution>
			        <execution>
			            <id>verify</id>
			            <phase>verify</phase>
			            <goals>
			                <goal>stop</goal>
			            </goals>
			        </execution>
			    </executions>
			</plugin>

		</plugins>
	</build>`

**Comment by vidalfontoura** [comment]
I'm having the same problem..
Can someone take a look into?

**Comment by vidalfontoura** [comment]
@straumat I may have found the solution.
I added the dependency 

`	<dependency>
			<groupId>org.mock-server</groupId>
			<artifactId>mockserver-netty</artifactId>
			<version>3.10.2</version>
		</dependency>
`
In the dependencies section and started working.

**Comment by straumat** [comment]
Thanks ! I will take a look at it !

**Comment by straumat** [comment]
Still doesn't work for me :(
