### ISSUE TITLE
Registering mock client fails with DEBUG logging on 

### ISSUE THREAD

**Issue by StuSchrader** [jamesdbloom/mockserver#249]
Version: 
mockserver-core-3.10.4.jar
netty-all-4.0.33.Final.jar

Ran across what I think is a bug.  When setting up mock server client in my Spock test, the server cannot set up properly because of an exception when logging the client setup in DEBUG mode. Exception is below.  

I am attaching the sample test I wrote that demonstrates the failure. Simply changing the log level to INFO on line 53 ceases the problem.

Thanks,

Stu

[TestMockServer.groovy.zip](https://github.com/jamesdbloom/mockserver/files/300588/TestMockServer.groovy.zip)

**Exception:**

`09:11:54.639 [nioEventLoopGroup-3-1] WARN org.mockserver.mockserver.MockServerHandler - Exception caught by MockServer handler closing pipeline
java.lang.IndexOutOfBoundsException: index: 16, length: 16 (expected: range(0, 16))
    at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1142)
    at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1137)
    at io.netty.buffer.PooledHeapByteBuf.internalNioBuffer(PooledHeapByteBuf.java:234)
    at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:558)
    at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:978)
    at org.mockserver.logging.LoggingHandler.formatByteBuf(LoggingHandler.java:221)
    at org.mockserver.logging.LoggingHandler.formatByteBufHolder(LoggingHandler.java:252)
    at org.mockserver.logging.LoggingHandler.formatMessage(LoggingHandler.java:185)
    at org.mockserver.logging.LoggingHandler.logMessage(LoggingHandler.java:170)
    at org.mockserver.logging.LoggingHandler.channelRead(LoggingHandler.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:240)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by jamesdbloom** [comment]
This issue has been fixed due to changes in the LoggerHandler and upgrades to the Netty version.  I can't reproduce this issue with the identical code.
