### ISSUE TITLE
java.io.IOException: An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by wilharri** [jamesdbloom/mockserver#278]
I started seeing this issue after I migrated from maven to gradle. Occasionally I experienced this issue with maven as well, but restarting IntelliJ usually fixed the issue. Since migrating to gradle, this issue happens 100% of the time. I'm on Windows 7.

`[ WARN] 14:15:27 [nioEventLoopGroup-3-5] Exception caught by MockServer handler closing pipeline []
java.io.IOException: An established connection was aborted by the software in your host machine
    at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_65]
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_65]
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_65]
    at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_65]
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_65]
    at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:221) ~[netty-buffer-4.0.34.Final.jar:4.0.34.Final]
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:898) ~[netty-buffer-4.0.34.Final.jar:4.0.34.Final]
    at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242) ~[netty-transport-4.0.34.Final.jar:4.0.34.Final]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-common-4.0.34.Final.jar:4.0.34.Final]
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.0.34.Final.jar:4.0.34.Final]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]`

**Comment by jamesdbloom** [comment]
Does it cause are particular issues, does the build still appear to run correctly?

Do you know at what stage of the build this occurs?

I would suspect it is caused by one or more process being killed (possibly by gradle) before they've had a chance to "properly" close all their open sockets.  Also some processes expect the server to close the socket but don't properly indicate that so when the client dies there are some sockets that are still open.  It may be some other issue however so it would be good to know as much as possible to rule any more important issue out.

**Comment by jamesdbloom** [comment]
This error is harmless however I have made some improvements to avoid this error from exposed, to the extend possible.

**Comment by MamedYahyayev** [comment]
I changed the localhost port and the problem solved
