### ISSUE TITLE
NoClassDefFoundError when creating server

### ISSUE THREAD

**Issue by khanh-nguyen** [jamesdbloom/mockserver#279]
MockServer Version: 3.10.4
I setup the test as in the doc
```java
public class TestClient {
    private ClientAndServer mockServer;
    @Before
    public void setup() {
        mockServer = startClientAndServer(8099);
        mockServer
                .when(request().withPath("/some/path"))
                .respond(response().withStatusCode(200).withHeader("Content-Type", "application/json"));
    }

    @Test
    public void test() {
        ...
    }
```
However, I get error right the line `mockServer = startClientAndServer(8099);`
```
java.lang.NoClassDefFoundError: com/google/common/collect/EvictingQueue

	at org.mockserver.filters.RequestLogFilter.<init>(RequestLogFilter.java:27)
	at org.mockserver.mockserver.MockServer.<init>(MockServer.java:34)
	at org.mockserver.integration.ClientAndServer.<init>(ClientAndServer.java:20)
	at org.mockserver.integration.ClientAndServer.startClientAndServer(ClientAndServer.java:29)
	at com.opower.dyn.TestSendApi.setup(TestClient.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.EvictingQueue
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 27 more
```

**Comment by khanh-nguyen** [comment]
@jamesdbloom turns out Guava is needed as dependency. It's probably was missing in the pom?

**Comment by khanh-nguyen** [comment]
I've checked. Guava is actually listed as dependency for mockserver-netty. So I'm not sure what the issue was but adding guava solved my problem.
