### ISSUE TITLE
Direct proxy forces SSL

### ISSUE THREAD

**Issue by igr** [jamesdbloom/mockserver#298]
I have the following test:

https://github.com/oblac/jodd/blob/master/jodd-http/src/test/java/jodd/http/ProxyTest.java#L80

I was expecting this one to works, in the same way as `testSocks5Proxy` works. However, for some reason, mockserver throws the following:

```
[00:13:24.929 [nioEventLoopGroup-3-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x794c24d1, /127.0.0.1:62457 => /127.0.0.1:1080] FLUSH
00:13:24.932 [main] DEBUG o.m.client.netty.NettyHttpClient - Received response: {
  "statusCode" : 201,
  "headers" : [ {
    "name" : "Connection",
    "values" : [ "keep-alive" ]
  }, {
    "name" : "Content-Length",
    "values" : [ "0" ]
  }, {
    "name" : "Content-Type",
    "values" : [ "text/plain" ]
  } ]
}
00:13:24.937 [nioEventLoopGroup-3-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x794c24d1, /127.0.0.1:62457 => /127.0.0.1:1080] FLUSH
00:13:24.938 [nioEventLoopGroup-3-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x794c24d1, /127.0.0.1:62457 :> /127.0.0.1:1080] INACTIVE
00:13:24.939 [nioEventLoopGroup-3-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x794c24d1, /127.0.0.1:62457 :> /127.0.0.1:1080] UNREGISTERED
00:13:24.947 [nioEventLoopGroup-6-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 3 thread-local buffer(s) from thread: nioEventLoopGroup-6-1
00:14:04.515 [nioEventLoopGroup-5-1] DEBUG org.mockserver.socket.SSLFactory - Using protocol TLSv1.2
00:14:04.629 [nioEventLoopGroup-5-1] DEBUG io.netty.util.internal.Cleaner0 - java.nio.ByteBuffer.cleaner(): available
00:14:04.641 [nioEventLoopGroup-5-1] WARN  o.m.proxy.relay.RelayConnectHandler - Exception caught by upstream relay handler -> closing pipeline [id: 0x314fce9c, /127.0.0.1:62458 => /127.0.0.1:1090]
io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f6765745f626f6f6b7320485454502f312e310d0a436f6e6e656374696f6e3a20436c6f73650d0a486f73743a206c6f63616c686f73743a313038300d0a557365722d4167656e743a204a6f646420485454500d0a0d0a
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:924) ~[netty-handler-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:369) [netty-codec-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) [netty-codec-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-common-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.0.34.Final.jar:4.0.34.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
](url)
```

Why this SSL error, when I am _not_ using SSL?

**Comment by PetRay** [comment]
Are you using HTTP CONNECT?
I am having a similar issue where connections being proxied using HTTP CONNECT always assume SSL.  I finally debugged this and I can see the following logic in org.mockserver.proxy.http.HttpProxyHandler:

if (request.getMethod().getValue().equals("CONNECT")) {
                // assume CONNECT always for SSL
                PortUnificationHandler.enabledSslUpstreamAndDownstream(ctx.channel());
                // add Subject Alternative Name for SSL certificate
                SSLFactory.addSubjectAlternativeName(request.getPath().getValue());

Why does it always assume SSL?  would be nice to have an option maybe in mockserver.properties to control this behavior.

**Comment by jamesdbloom** [comment]
That is a good point the main reason this is here is because HTTP CONNECT is used to proxy TLS connections.  This is also here because SOCKS does support a mechanism to indicate if the proxied connection is TLS or not.

I'm currently looking at resolving any issue with badly behaving TLS servers, once that it fixed I'll take a look at this.

**Comment by jamesdbloom** [comment]
This is now resolved so closing this issue, I will release in next 2/3 days with this fix.
