### ISSUE TITLE
null pointer exception at match time for expectations with null parameter values - error should be thrown earlier

### ISSUE THREAD

**Issue by liront2** [jamesdbloom/mockserver#312]
Although expectation is created successfully, when I query the mock-server the logs show:

2017-02-06 19:09:21,689 ERROR o.m.m.MockServerHandler Exception processing {
  "method" : "POST",
  "path" : "/health",
  "headers" : [ {
    "name" : "Host",
    "values" : [ "localhost:1080" ]
  }, {
    "name" : "Connection",
    "values" : [ "keep-alive" ]
  }, {
    "name" : "Content-Length",
    "values" : [ "0" ]
  }, {
    "name" : "Accept",
    "values" : [ "application/json" ]
  }, {
    "name" : "Cache-Control",
    "values" : [ "no-cache" ]
  }, {
    "name" : "Origin",
    "values" : [ "chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop" ]
  }, {
    "name" : "User-Agent",
    "values" : [ "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36" ]
  }, {
    "name" : "Content-Type",
    "values" : [ "application/json" ]
  }, {
    "name" : "Postman-Token",
    "values" : [ "c27b920b-f917-f8b8-c78a-71d0a24e9884" ]
  }, {
    "name" : "X-Zooz-Request-Id",
    "values" : [ "123e4567-e89b-12d3-a456-426655440000" ]
  }, {
    "name" : "DNT",
    "values" : [ "1" ]
  }, {
    "name" : "Accept-Encoding",
    "values" : [ "gzip, deflate, br" ]
  }, {
    "name" : "Accept-Language",
    "values" : [ "he,en-US;q=0.8,en;q=0.6,ru;q=0.4,ja;q=0.2,zh-CN;q=0.2,zh;q=0.2,zh-TW;q=0.2" ]
  } ],
  "keepAlive" : true,
  "secure" : false
}
java.lang.NullPointerException: null
	at org.mockserver.collections.CaseInsensitiveRegexMultiMap.containsAll(CaseInsensitiveRegexMultiMap.java:50) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.matchers.MultiValueMapMatcher.matches(MultiValueMapMatcher.java:24) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.matchers.MultiValueMapMatcher.matches(MultiValueMapMatcher.java:12) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.matchers.HttpRequestMatcher.matches(HttpRequestMatcher.java:226) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.matchers.HttpRequestMatcher.matches(HttpRequestMatcher.java:181) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.mock.Expectation.matches(Expectation.java:148) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.mock.MockServerMatcher.handle(MockServerMatcher.java:61) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.mockserver.MockServerHandler.channelRead0(MockServerHandler.java:165) [mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.mockserver.MockServerHandler.channelRead0(MockServerHandler.java:41) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.server.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:115) [mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.server.unification.PortUnificationHandler.channelRead0(PortUnificationHandler.java:45) [mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.server.unification.PortUnificationHandler.channelRead0(PortUnificationHandler.java:25) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [mockserver-netty-jar-with-dependencies.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

Please help!!

Thanks,
Liron

**Comment by AnisimovAleksandr** [comment]
Show your expectation (which you send to mockserver)

**Comment by liront2** [comment]
When sending null in one of the values.

2017-02-20 15:00:31,378 ERROR o.m.p.h.HttpProxyHandler Exception processing {
  "method" : "PUT",
  "path" : "/verify",
  "headers" : [ {
    "name" : "Content-Type",
    "values" : [ "application/json; charset=utf-8" ]
  }, {
    "name" : "Host",
    "values" : [ "10.100.11.28:1090" ]
  }, {
    "name" : "Connection",
    "values" : [ "close" ]
  }, {
    "name" : "Content-Length",
    "values" : [ "1093" ]
  } ],
  "keepAlive" : false,
  "secure" : false,
  "body" : {
    "charset" : "UTF-8",
    "type" : "STRING",
    "string" : "{\"httpRequest\":{\"method\":\"POST\",\"path\":\"/order/alu/v3\",\"body\":{\"type\":\"PARAMETERS\",\"parameters\":[{\"name\":\"BILL_COUNTRYCODE\",\"values\":[null]},{\"name\":\"BILL_ADDRESS\",\"values\":[\"Washington 35\"]},{\"name\":\"BILL_ADDRESS2\",\"values\":[\"apt 203\"]},{\"name\":\"BILL_FNAME\",\"values\":[\"Johnny\"]},{\"name\":\"BILL_LNAME\",\"values\":[\"Cash\"]},{\"name\":\"BILL_CITY\",\"values\":[\"New-York\"]},{\"name\":\"BILL_PHONE\",\"values\":[\"186293774397\"]},{\"name\":\"BILL_ZIPCODE\",\"values\":[\"11111\"]},{\"name\":\"BILL_STATE\",\"values\":[\"NY\"]},{\"name\":\"BILL_CITYPE\",\"values\":[\"passport\"]},{\"name\":\"BILL_CINUMBER\",\"values\":[\"12345678\"]},{\"name\":\"BILL_EMAIL\",\"values\":[\"buyer1@gmail.com\"]},{\"name\":\"DELIVERY_ADDRESS\",\"values\":[\"Hayovel 34\"]},{\"name\":\"DELIVERY_ADDRESS2\",\"values\":[\"apt 1\"]},{\"name\":\"DELIVERY_CITY\",\"values\":[\"Holon\"]},{\"name\":\"DELIVERY_COUNTRYCODE\",\"values\":[\"ISR\"]},{\"name\":\"DELIVERY_FNAME\",\"values\":[\"Gill\"]},{\"name\":\"DELIVERY_LNAME\",\"values\":[\"Cohen\"]},{\"name\":\"DELIVERY_PHONE\",\"values\":[\"97231111111\"]},{\"name\":\"DELIVERY_STATE\",\"values\":[\"\"]},{\"name\":\"DELIVERY_ZIPCODE\",\"values\":[\"596342\"]}]}},\"times\":{\"count\":1,\"exact\":true}}"
  }
}
java.lang.NullPointerException: null
	at org.mockserver.collections.CaseInsensitiveRegexMultiMap.containsAll(CaseInsensitiveRegexMultiMap.java:50) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.matchers.MultiValueMapMatcher.matches(MultiValueMapMatcher.java:24) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.matchers.ParameterStringMatcher.matches(ParameterStringMatcher.java:26) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.matchers.ParameterStringMatcher.matches(ParameterStringMatcher.java:16) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.matchers.HttpRequestMatcher.matches(HttpRequestMatcher.java:226) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.matchers.HttpRequestMatcher.matches(HttpRequestMatcher.java:175) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.filters.RequestLogFilter.verify(RequestLogFilter.java:104) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.proxy.http.HttpProxyHandler.channelRead0(HttpProxyHandler.java:121) [mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.proxy.http.HttpProxyHandler.channelRead0(HttpProxyHandler.java:42) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [mockserver-netty-jar-with-dependencies.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

**Comment by AnisimovAleksandr** [comment]
Show your EXPECTATION (not exception) (which you send to mockserver; part of java-code).

**Comment by jamesdbloom** [comment]
As @AnisimovAleksandr mentioned above please provide the code you are using to create the expectation then it should be easy to resolve your problem.

**Comment by jamesdbloom** [comment]
This is happening because your parameter value for `BILL_COUNTRYCODE` is null in your verification or your expectation.  If you want to represent no value please don't specify a value.  Specifying `null` is not allowed.

I will add some logic to ensure that when an exception is added with a null value like this an error is thrown immediately, instead of when the exception is compared against an incoming request.

**Comment by jamesdbloom** [comment]
I have now added JSON schema validation for all endpoints so you should no longer have issues with expectations, because when you attempt to create an invalid expectation you will receive a validation error.

**Comment by liront2** [comment]
Thanks so much!!!!

LironT
