### ISSUE TITLE
A specific url give SSL handshake error 

### ISSUE THREAD

**Issue by khalidse** [jamesdbloom/mockserver#320]
We have an automation project using selenium and we are using proxy to list browser network calls. We tried to use Mockserver which is working good for both http and https requests, but we have an issue with a specific url "https://content.jwplatform.com/libraries/d8kYgPIS.js". We connect browser to Mockserver but the above url always crash with (SSL handshake error) meanwhile all other https links works normally.

Certificates for Mockserver installed in trusted store certificates. also i have update java security jar files.

Is there anyway i could work around this error ?

Also to note this error happen in OSX, linux and windows.

**Comment by jamesdbloom** [comment]
I'm looking into this

**Comment by jamesdbloom** [comment]
Here is the stack trace for this issue:

```bash
2017-05-06 22:01:16,228 ERROR o.m.p.h.HttpProxyHandler Exception processing {
  "method" : "GET",
  "path" : "/libraries/d8kYgPIS.js",
  "headers" : [ {
    "name" : "Host",
    "values" : [ "localhost:1090" ]
  }, {
    "name" : "Pragma",
    "values" : [ "no-cache" ]
  }, {
    "name" : "Cache-Control",
    "values" : [ "no-cache" ]
  }, {
    "name" : "Upgrade-Insecure-Requests",
    "values" : [ "1" ]
  }, {
    "name" : "User-Agent",
    "values" : [ "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36" ]
  }, {
    "name" : "Accept",
    "values" : [ "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" ]
  }, {
    "name" : "Accept-Encoding",
    "values" : [ "gzip, deflate, sdch, br" ]
  }, {
    "name" : "Accept-Language",
    "values" : [ "en-US,en;q=0.8,fa;q=0.6" ]
  }, {
    "name" : "content-length",
    "values" : [ "0" ]
  } ],
  "keepAlive" : true,
  "secure" : true
}
java.lang.RuntimeException: Exception while sending request
	at org.mockserver.client.netty.NettyHttpClient.sendRequest(NettyHttpClient.java:86) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.proxy.http.HttpProxyHandler.sendRequest(HttpProxyHandler.java:182) [mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.proxy.http.HttpProxyHandler.channelRead0(HttpProxyHandler.java:161) [mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.proxy.http.HttpProxyHandler.channelRead0(HttpProxyHandler.java:44) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1228) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1039) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [mockserver-netty-jar-with-dependencies.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.util.concurrent.ExecutionException: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:272) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.client.netty.NettyHttpClient.sendRequest(NettyHttpClient.java:62) ~[mockserver-netty-jar-with-dependencies.jar:na]
	... 47 common frames omitted
Caused by: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) [mockserver-netty-jar-with-dependencies.jar:na]
	... 16 common frames omitted
Caused by: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[na:1.8.0_121]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[na:1.8.0_121]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[na:1.8.0_121]
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[na:1.8.0_121]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[na:1.8.0_121]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[na:1.8.0_121]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_121]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_121]
	at io.netty.handler.ssl.SslHandler$SslEngineType$2.unwrap(SslHandler.java:223) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1117) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1039) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [mockserver-netty-jar-with-dependencies.jar:na]
	... 16 common frames omitted
2017-05-06 22:01:16,652 ERROR o.m.p.h.HttpProxyHandler Exception processing {
  "method" : "GET",
  "path" : "/favicon.ico",
  "headers" : [ {
    "name" : "Host",
    "values" : [ "localhost:1090" ]
  }, {
    "name" : "Pragma",
    "values" : [ "no-cache" ]
  }, {
    "name" : "Cache-Control",
    "values" : [ "no-cache" ]
  }, {
    "name" : "User-Agent",
    "values" : [ "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36" ]
  }, {
    "name" : "Accept",
    "values" : [ "image/webp,image/*,*/*;q=0.8" ]
  }, {
    "name" : "Referer",
    "values" : [ "https://localhost:1090/libraries/d8kYgPIS.js" ]
  }, {
    "name" : "Accept-Encoding",
    "values" : [ "gzip, deflate, sdch, br" ]
  }, {
    "name" : "Accept-Language",
    "values" : [ "en-US,en;q=0.8,fa;q=0.6" ]
  }, {
    "name" : "content-length",
    "values" : [ "0" ]
  } ],
  "keepAlive" : true,
  "secure" : true
}
java.lang.RuntimeException: Exception while sending request
	at org.mockserver.client.netty.NettyHttpClient.sendRequest(NettyHttpClient.java:86) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.proxy.http.HttpProxyHandler.sendRequest(HttpProxyHandler.java:182) [mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.proxy.http.HttpProxyHandler.channelRead0(HttpProxyHandler.java:161) [mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.proxy.http.HttpProxyHandler.channelRead0(HttpProxyHandler.java:44) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1228) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1039) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [mockserver-netty-jar-with-dependencies.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.util.concurrent.ExecutionException: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:272) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.client.netty.NettyHttpClient.sendRequest(NettyHttpClient.java:62) ~[mockserver-netty-jar-with-dependencies.jar:na]
	... 47 common frames omitted
Caused by: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) [mockserver-netty-jar-with-dependencies.jar:na]
	... 16 common frames omitted
Caused by: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[na:1.8.0_121]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[na:1.8.0_121]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[na:1.8.0_121]
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[na:1.8.0_121]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[na:1.8.0_121]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[na:1.8.0_121]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_121]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_121]
	at io.netty.handler.ssl.SslHandler$SslEngineType$2.unwrap(SslHandler.java:223) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1117) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1039) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [mockserver-netty-jar-with-dependencies.jar:na]
	... 16 common frames omitted
```

**Comment by jamesdbloom** [comment]
I think I have the fix for this it is related to using the SNI (Extension server_name) from the client.  It seems that certain server expect this extension to be present in the request or the SSL handshake fails.  I'm just fully testing then I submit the fix and do a release in the next couple of days.

**Comment by jamesdbloom** [comment]
This is now fixed, there will be a release including this fix in the next 2/3 days.
