### ISSUE TITLE
MockServer unable to handle big post requests over WebSockets

### ISSUE THREAD

**Issue by bramhaze** [jamesdbloom/mockserver#337]
To start, I really like this project and how it functions. I ran into one problem though, which is related to the fact that WebSockets from Netty are used.

First of all. The setup that I use is MockServer with the netty server start-up.

The set-up code which triggers the problem is about:

mockServer = startClientAndServer(port);

        mockServer
                .when(
                        request()
                                .withMethod("POST"), Times.unlimited())
                .callback(callbackHandler); // Where callbackHandler is handling the requests

The problem that occurs now is the following. If a POST request is done with a body of more then 65536 bytes an exception occurs (see below). Diving into netty a bit with decompiling and googling didn't lead to a solution to up this limit of 65536 for handling websockets.

This limitation is really a pity, it would be great if there would be a solution or workaround.

Exception:
ERROR o.m.c.n.w.WebSocketClientHandler web socket client caught exception
io.netty.handler.codec.CorruptedFrameException: Max frame length of 65536 has been exceeded.
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:412) ~[mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:277) ~[mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) [mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565) [mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479) [mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) [mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [mockserver-netty-3.10.7-jar-with-dependencies.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]

With kind regard,

Bram

**Comment by bramhaze** [comment]
After doing a quick check through the code I suspect the cause to be in the module mockserver-netty in class  org.mockserver.mockserver.callback.WebSocketServerHandler.

In the function upgradeChannel the actual websocket is made, it uses the limited constructor from netty (WebSocketServerHandshakerFactory) where no maxFramePayloadLength is entered so netty fills in 65536 hardcoded. (See code snippet below.)

    private void upgradeChannel(final ChannelHandlerContext ctx, FullHttpRequest httpRequest) {
        handshaker = new WebSocketServerHandshakerFactory(
                "ws://" + httpRequest.headers().get(HOST) + WEB_SOCKET_URI,
                null,
                true **<-- here netty puts in the hardcoded 65536 packframe size**
        ).newHandshaker(httpRequest);
        if (handshaker == null) {
            WebSocketServerHandshakerFactory.sendUnsupportedVersionResponse(ctx.channel());
        } else {
            final String clientId = UUID.randomUUID().toString();
            handshaker.handshake(
                    ctx.channel(),
                    httpRequest,
                    new DefaultHttpHeaders().add("X-CLIENT-REGISTRATION-ID", clientId),
                    ctx.channel().newPromise()
            ).addListener(new ChannelFutureListener() {
                @Override
                public void operationComplete(ChannelFuture future) throws Exception {
                    webSocketClientRegistry.registerClient(clientId, ctx);
                    // TODO(jamesdbloom) remove mockserver codec and handler
                }
            });
        }
    }

**Comment by jamesdbloom** [comment]
I have increased the WebSocket frame size to `Integer.MAX_VALUE` so there shouldn't be an issue with large frames.  I will also add an additional integration test to confirm this and close the ticket.

**Comment by jamesdbloom** [comment]
I have now added a test showing it is possible to send 65536*10 bytes.  It should actually be possible to send 2147483647 bytes but I don't want an integration test to cover this scenario due to memory limitations on build server.

I am going to close this ticket a new MockServer release will be made in the next few days which will include this fix.
