### ISSUE TITLE
AbstractClient throws NPE

### ISSUE THREAD

**Issue by johndevs** [jamesdbloom/mockserver#384]
This works with 3.10.4

```
ClientAndProxy proxy = startClientAndProxy(1090);
String json = proxy.retrieveAsJSON(null);
``` 
But stops working with 3.11:
```
    java.lang.IllegalArgumentException: 1 error:
     - a request is required but value was "null"
        at org.mockserver.client.AbstractClient.sendRequest(AbstractClient.java:78)
        at org.mockserver.client.proxy.ProxyClient.retrieveAsJSON(ProxyClient.java:250)
        at org.mockserver.client.proxy.ProxyClient$retrieveAsJSON.call(Unknown Source)
```

This is because ``ClientAndProxy.retrieveAsJSON()`` accepts and handles null values but ``AbstractClient.sendRequest()`` can no longer handle them.

**Comment by jamesdbloom** [comment]
From you code it looks like the AbstractClient is throwing an `IllegalArgumentException` not a NPE.

I don't understand how the explanation can be correct, as the following unit test covers that case:

```java

    @Test
    public void shouldReceiveExpectationsAsJSONWithNullRequest() throws UnsupportedEncodingException {
        // given
        String expectations = "body";
        when(mockHttpClient.sendRequest(any(HttpRequest.class))).thenReturn(response().withBody("body"));

        // when
        assertEquals(expectations, proxyClient.retrieveAsJSON(null));

        // then
        verify(mockHttpClient).sendRequest(request().withHeader(HOST.toString(), "localhost:" + 1090).withMethod("PUT").withPath("/retrieve").withBody(""));
    }
```

In addition the `httpRequest` parameter of `retrieveAsJSON` is the body of the `httpRequest` parameter of `sendRequest`.  The following code of the `retrieveAsJSON` method shows how that works:

```java
    public String retrieveAsJSON(HttpRequest httpRequest) {
        HttpResponse httpResponse = sendRequest(request().withMethod("PUT").withPath(calculatePath("retrieve")).withBody(httpRequest != null ? httpRequestSerializer.serialize(httpRequest) : ""));
        return httpResponse.getBodyAsString();
    }
```

Can you provide more information so I can track down the cause of the `IllegalArgumentException`.
