### ISSUE TITLE
mockserver-maven-plugin:5.2.3:run results to java.lang.NullPointerException at org.mockserver.maven.MockServerRunAndWaitMojo.execute(MockServerRunAndWaitMojo.java:34)

### ISSUE THREAD

**Issue by franz-see** [jamesdbloom/mockserver#400]
Given POM

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ph.net.ph</groupId>
    <artifactId>mock-server-trial</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>mock-server-trial</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.mock-server</groupId>
                <artifactId>mockserver-maven-plugin</artifactId>
                <version>5.2.3</version> <!-- build error -->
                <!--<version>3.11</version>--> <!-- works -->
                <configuration>
                    <serverPort>1080</serverPort>
                    <proxyPort>1090</proxyPort>
                    <logLevel>DEBUG</logLevel>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

```

And command `mvn mockserver:run -X`

I expect mockserver to run.

But I got 

```
$ mvn mockserver:run -X
...
[ERROR] Exception while running MockServer
java.lang.NullPointerException
	at org.mockserver.maven.MockServerRunAndWaitMojo.execute(MockServerRunAndWaitMojo.java:34)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.595 s
[INFO] Finished at: 2017-12-19T21:03:40+08:00
[INFO] Final Memory: 15M/113M
```

[mockserver-run-build.log](https://github.com/jamesdbloom/mockserver/files/1571723/mockserver-run-build.log)

**Comment by jamesdbloom** [comment]
This is now fixed, unfortunately the commit where tagged against #300 instead of #400.

**Comment by harshadambulkar-hexaware** [comment]
[INFO] no matching expectation - returning:

	{
	  "statusCode" : 404,
	  "reasonPhrase" : "Not Found"
	}

 for request:

	{
	  "method" : "POST",
	  "path" : "/RESTfulExample/json/product/post",
	  "body" : {
	    "type" : "STRING",
	    "string" : "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<employees>\n\t<employee>\n\t\t<id>idp</id>\n\t\t<PSI>id</PSI>\n\t\t</employee>\n</employees>  ",
	    "contentType" : "text/plain; charset=utf-8"
	  },
	  "headers" : {
	    "Connection" : [ "Keep-Alive" ],
	    "User-Agent" : [ "Apache-HttpClient/4.1.1 (java 1.5)" ],
	    "Host" : [ "localhost:1080" ],
	    "Accept-Encoding" : [ "gzip,deflate" ],
	    "Content-Length" : [ "123" ],
	    "Content-Type" : [ "application/xml" ]
	  },
	  "keepAlive" : true,
	  "secure" : false
	}
how to solve 404
