### ISSUE TITLE
https requests failing with: java.lang.IllegalStateException: Trying to connect to remote socket but no remote socket has been set

### ISSUE THREAD

**Issue by marcaractac** [jamesdbloom/mockserver#405]
Hey there, 

I'm new to MockServer and am just trying to run an Android phone through the proxy running on OSX (Sierra 10.12.6). I'm seeing the following stack trace, and cannot get passed the remote socket issue. On the phone, I'm using the Mac's IP as the proxy hostname, and am using the correct proxy server port I initially set. I also have the certificate installed on the phone. Any help would be greatly appreciated.

Thanks, 
Marc

$ java -jar mockserver-netty-5.3.0-jar-with-dependencies.jar -serverPort 1080 -proxyPort 1090 -proxyRemotePort 80 -proxyRemoteHost www.mock-server.com
2018-01-08 15:23:16,372 INFO o.m.m.MockServer MockServer started on port: 1080
2018-01-08 15:23:16,565 INFO o.m.p.d.DirectProxy MockServer started on port: 1090
2018-01-08 15:38:25,874 WARN o.m.p.r.RelayConnectHandler Exception caught by CONNECT proxy handler -> closing pipeline 
java.lang.IllegalStateException: Trying to connect to remote socket but no remote socket has been set
	at org.mockserver.proxy.relay.RelayConnectHandler.getDownstreamSocket(RelayConnectHandler.java:115) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at org.mockserver.proxy.relay.RelayConnectHandler.channelRead0(RelayConnectHandler.java:98) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at org.mockserver.mockserver.MockServerHandler.channelRead0(MockServerHandler.java:103) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at org.mockserver.mockserver.MockServerHandler.channelRead0(MockServerHandler.java:37) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at org.mockserver.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:188) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at org.mockserver.unification.PortUnificationHandler.channelRead0(PortUnificationHandler.java:91) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at org.mockserver.unification.PortUnificationHandler.channelRead0(PortUnificationHandler.java:37) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

**Comment by jamesdbloom** [comment]
Which proxy port are you using?

For your use case you don't need to provide the `--serverPort` argument.

I have just double checked you use case as follows:

`java -jar mockserver-netty-5.3.0-jar-with-dependencies.jar -proxyPort 1090 -proxyRemotePort 80 -proxyRemoteHost www.mock-server.com`

Then the curl command:

`curl -v "http://localhost:1090/index.html" --header "Host: www.mock-server.com"`

**Comment by marcaractac** [comment]
If you mean which proxy port I'm using on the phone, I had 1080 there. I changed it to 1090 and then did what you said, but now I get:

2018-01-09 09:06:38,044 WARN o.m.p.r.RelayConnectHandler Exception caught by downstream relay handler -> closing pipeline [id: 0xfe1ee157, L:0.0.0.0/0.0.0.0:56963 ! R:www.mock-server.com/52.84.27.251:80]

When trying to load a website on the phone, I just get a bad request error

**Comment by marcaractac** [comment]
I've recently returned to working on this, still not having any luck and getting the same error as in the above post.

**Comment by marcaractac** [comment]
I've gotten this to work after. The only change I had to make based off of your suggestion was to also remove setting the proxy remote host. Thank you!

**Comment by jamesdbloom** [comment]
So I suspect you had set the MockServer on your phone as a proxy?

MockServer support HTTP, HTTPS and SOCKS proxying so if you configure your HTTP client to use MockServer as a proxy then it proxies your request.

The proxy remote host is for port forwarding where all request are forwarded automatically to the remote port without configuring your HTTP client.

**Comment by marcaractac** [comment]
That is correct

**Comment by marcaractac** [comment]
I do have a quick unrelated question. I'm trying to set an expectation that runs an unlimited amount of times but cannot get things to work. I'm using Ruby, and the only example of this I've found is at this [link](http://www.matthewbussa.com/2016/07/mock-server.html) but doing it this way throws:

/Users/marc/.rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!': 400 Bad Request (RestClient::BadRequest)

I figure I'm just using the unlimited method incorrectly, but if not, I can definitely supply more info on the errors I'm getting.

**Comment by marcaractac** [comment]
I'm currently now trying to get things running on iOS the same way I have already on Android. For the time being, I have the proxy set up on the phone and am loading websites/apps to see what the terminal spits out. Some things work, like google, yahoo, but most things do not, like apps and the app store itself are unable to connect. This is what I get when trying to load anything that does not connect:

2018-02-08 13:27:49,393 WARN o.m.u.PortUnificationHandler Exception caught by port unification handler -> closing pipeline [id: 0xdfa836b3, L:0.0.0.0/0.0.0.0:1090 ! R:/192.168.5.62:62278]
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received close_notify during handshake
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
Caused by: javax.net.ssl.SSLException: Received close_notify during handshake
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:214) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1762) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1725) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1878) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl.processInputRecord(SSLEngineImpl.java:1140) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1020) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:902) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:680) ~[na:na]
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:626) ~[na:na]
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:292) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1247) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1158) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1193) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	... 16 common frames omitted


I've tried setting the proxy using the wifi settings as well as using Apple Configurator to set a Global HTTP proxy, and I get the same results either way. As for proxy server and port, I'm using the exact same info as I have on Android, which functions exactly as intended. Any ideas on what can be causing this?

**Comment by jamesdbloom** [comment]
As first glance this looks like a socket you are connecting to is being closed before the SSL handshake has completed.  This often happens if you stop MockServer while you are in the middle of proxying content or responding to expectations.  Normally this can be ignored because basically it is saying "can't complete SSL handshake due to be shutdown".

1. when do you see these errors?
2. are they causing any particular failure or just errors the log?
3. where do you see these, i.e. in the console or in a log?

**Comment by marcaractac** [comment]
Browsing websites in Safari on the iPhone is the only time I see correct web traffic with mockserver running in a console. Anything involving apps throw these errors.  

I basically need to see the requests/responses coming from an app in order to write scripts to mock said data for testing. 

Doing this has been successful on Android. I've also set up Charle's proxy on the iPhone just for the sake of seeing if I could get web traffic from the app, and it was successful there. Of course, Charles is not very useful for automated testing whereas mockserver is perfect for it.

**Comment by marcaractac** [comment]
I have been working with Android more for the time being, as I currently cannot do anything on iOS due to the port unification handler exceptions I've been getting. But I have also encountered the same issue in some cases on Android as well. 

There are several cases where the app will hit up a local server to acquire data, which I need to mock for automated tests. I've written one that works, but when I try for another, it throws the port unification handler exception much like what I've been dealing with using iOS. 

As with iOS, when I run an Android phone using Charle's proxy software, these same scenarios that throw exceptions on mockserver are working fine.

**Comment by moldis** [comment]
I have same issue, only with HTTPS. Everytime mockserver just exception this error. All certs are installed on both sides: android emulator and windows

**Comment by marcaractac** [comment]
Yeah I haven't been able to figure out a fix either. Really does not seem to be an issue on my end at this point. Hoping to circle back to it at some point soon.

**Comment by jamesdbloom** [comment]
Has there been any progress on this?  

In particular, have you been able to determine if apps are allowing the MockServer CA certificate as a trusted certificate?  If the apps are not trusting the MockServer CA certificate they may be closing the socket before the TLS handshake has been completed thus the error you've seen.  This seems like the most like cause of this issue especially as you say it works fine in browsers.  How did you configure your apps to trust the Charles CA certificate?

Do you have any apps using plain HTTP because I imagine this works?  

Have you tried this in the latest version of MockServer?

**Comment by jamesdbloom** [comment]
The remaining questions on this issue are covered by a more recent issue #455 so I'm closing this issue please add any comments to #457.
