### ISSUE TITLE
java.io.IOException: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by rodrigobelo** [jamesdbloom/mockserver#406]
Hi guys,

I'm facing a trouble with MockServer that when run a GET request on my c# code I get the following error:

`2018-01-09 14:38:40,273 ERROR [nioEventLoopGroup-3-2] o.m.m.c.WebSocketServerHandler [?:?] web socket server caught exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[na:1.8.0_151]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[na:1.8.0_151]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[na:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[na:1.8.0_151]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_151]
2018-01-09 14:39:11,455 ERROR [nioEventLoopGroup-3-1] o.m.m.c.WebSocketServerHandler [?:?] web socket server caught exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[na:1.8.0_151]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[na:1.8.0_151]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[na:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[na:1.8.0_151]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_151]
2018-01-09 14:59:51,107 DEBUG [main] org.mockserver.cli.Main [?:?] 

Using command line options: proxyPort=7778, serverPort=7777`

At my c# I received an exception:
System.Net.Http.HttpRequestException: 'Error while copying content to a stream.'

I found that maybe the Netty version have a problem: https://github.com/netty/netty/issues/6426

Can anyone help me figure this out?

Thank you!

**Comment by rodrigobelo** [comment]
About my environment:
jre1.8.0_151
Win 10

**Comment by jamesdbloom** [comment]
The error is a standard error thrown when the client unexpectedly closes its connection, i.e. your C# code has closed the connection.

The link you provide is not relevant and refers to Netty version 4.1.**7**, MockServer usese version 4.1.**17**.  In addition this bug only share a generic connection closure issue but nothing else. 

I would suspect that your C# is closing the connecting after incorrectly connecting to the MockServer WebSocket endpoint.

Before I could help, I would need information on what you are trying to do and the code that is causing the issue.

**Comment by jamesdbloom** [comment]
I don't believe this issue is related to any logic in MockServer so I am going to close this issue.  If you can provide some code examples or evidence pointing to this being a bug in MockServer I will happily re-open the issue and investigate / resolve the issue.
