### ISSUE TITLE
retrieveLogMessagesArray => Channel set as inactive before valid response has been received

### ISSUE THREAD

**Issue by jimkohl** [jamesdbloom/mockserver#455]
**Issue**:   Channel set as inactive before valid response has been received

**Usecase**:
Using MS ClientAndServer and then direct SUT traffic via port redirection to the instantiated MS.  
I run a companion thread which periodically requests info from the ms, and gets it most of the time.

When retrieving Log Messages via:      
    String[] logArray = client.**retrieveLogMessagesArray**()

occasionally receiving this message:
      org.mockserver.client.netty.SocketConnectionException: 
               Channel set as inactive before valid response has been received

This is usually right after a service that generated a larger log profile, so I suspect its a timeout awaiting log array receipt.

**Alternative**:
if I break it up in smaller pieces (would prefer 1 call tho) exception does not occur.:
        String[] logArray = client.**retrieveLogMessagesArray** HttpRequest.request().withPath(path))

I don't see a setTimeout value on client, but suspect that might help.
Hope all is well James!
jim

**Comment by jimkohl** [comment]
Here's the exception I encountered in the above scenario:
Channel set as inactive before valid response has been received
org.mockserver.client.netty.SocketConnectionException: Channel set as inactive before valid response has been received
	at org.mockserver.client.netty.HttpClientConnectionHandler.updatePromise(HttpClientConnectionHandler.java:18)
	at org.mockserver.client.netty.HttpClientConnectionHandler.channelInactive(HttpClientConnectionHandler.java:24)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1409)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:927)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jimkohl** [comment]
I also experimented moving up the maxSocketTimeout; no difference ...    
   ConfigurationProperties.maxSocketTimeout(145000)

**Comment by jimkohl** [comment]
also ... ConfigurationProperties.socketConnectionTimeout(145000).  same.
My log level is set to INFO, and am getting the right balance of requests/responses/curls/etc.
However there are other messages in there that I filter out after receiving the payload (admin type messages).
One way to mitigate might be to narrow down which types of messages should be sent (beyond path, request type).  Knowing the care put into Mockserver there's probably a way to do this already ...

am attempting to retrieve all the log messages to check for matched expectations / unmatched (curl or 404)  only.  At the end of a session that can be a large payload of log messages, so filtering out unnecessary msgs before sending could help.  And there is a decent chance that many of those log messages are already gone.

**Comment by jamesdbloom** [comment]
@jimkohl have you retested this in MockServer 5.4.1.  I can reproduce this in the current code base when I have 500 expectations, 100s of requests logs, 100s or request responses logged.  Are you using the Netty or WAR version of MockServer?

**Comment by jimkohl** [comment]
James
I’ve been working on a diff project lately but let me dust off and see what I find. 
Jim

**Comment by jamesdbloom** [comment]
I believe this issue is now fixed in the latest versions of MockServer so I am closing this issue.  Please raise a new issue if you can reproduce the issue in the latest versions of MockServer.
