### ISSUE TITLE
Mock SAP call

### ISSUE THREAD

**Issue by leocborges** [jamesdbloom/mockserver#482]
I'd like to know if would be possible to mock a SAP call with `mock-server`.
I have read the docs and did some tests, but I wasn't able to figure out by myself yet.

I guess I need to proxy somehow the call, but I'm not sure how it should be done with stubs generated by wsdl.

Running locally without any connection to SAP I got this exception:
```
Caused by: java.net.UnknownHostException: sap
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
	at com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:104)
```
As it uses `sun.net.www.protocol.http.HttpURLConnection` class, which extends `java.net.HttpURLConnection`, I believe it is possible.

I have set `System.setProperty("http.proxyHost", "localhost");` and `System.setProperty("http.proxyPort", "1090");`, but it doesn't worked.
The SAP calls don't get proxied, just regular HTTP.

Thanks in advance.

**Comment by leocborges** [comment]
Got it!
Basically just need to set http and socket proxies and create expectations. Like:

        System.setProperty("http.proxyHost", "localhost");
        System.setProperty("http.proxyPort", port);
        System.setProperty("socksProxyHost", "localhost");
        System.setProperty("socksProxyPort", port);
