### ISSUE TITLE
Channel set as inactive before valid response has been received

### ISSUE THREAD

**Issue by StewartPan** [jamesdbloom/mockserver#489]
Hi, same issue as #420 
I used the source code to build. followed the instruction in [instrunction](http://www.mock-server.com/mock_server/running_mock_server.html#running_from_command_line).

After I type `man clean package`
the console displayed the following message:

[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.412 s <<< FAILURE! - in org.mockserver.client.netty.NettyHttpClientErrorHandlingTest
[ERROR] shouldHandleConnectionClosure(org.mockserver.client.netty.NettyHttpClientErrorHandlingTest)  Time elapsed: 0.103 s  <<< FAILURE!
java.lang.AssertionError:

Expected: (an instance of java.util.concurrent.ExecutionException and exception with message a string containing "Exception caught before valid response has been received")
     but: exception with message a string containing "Exception caught before valid response has been received" message was "org.mockserver.client.netty.SocketConnectionException: Channel set as inactive before valid response has been received"
Stacktrace was: java.util.concurrent.ExecutionException: org.mockserver.client.netty.SocketConnectionException: Channel set as inactive before valid response has been received
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:272)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
	at org.mockserver.client.netty.NettyHttpClientErrorHandlingTest.shouldHandleConnectionClosure(NettyHttpClientErrorHandlingTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
Caused by: org.mockserver.client.netty.SocketConnectionException: Channel set as inactive before valid response has been received
	at org.mockserver.client.netty.HttpClientConnectionHandler.updatePromise(HttpClientConnectionHandler.java:18)
	at org.mockserver.client.netty.HttpClientConnectionHandler.channelInactive(HttpClientConnectionHandler.java:24)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1409)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:927)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   NettyHttpClientErrorHandlingTest.shouldHandleConnectionClosure
Expected: (an instance of java.util.concurrent.ExecutionException and exception with message a string containing "Exception caught before valid response has been received")
     but: exception with message a string containing "Exception caught before valid response has been received" message was "org.mockserver.client.netty.SocketConnectionException: Channel set as inactive before valid response has been received"
Stacktrace was: java.util.concurrent.ExecutionException: org.mockserver.client.netty.SocketConnectionException: Channel set as inactive before valid response has been received
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:272)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
	at org.mockserver.client.netty.NettyHttpClientErrorHandlingTest.shouldHandleConnectionClosure(NettyHttpClientErrorHandlingTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
Caused by: org.mockserver.client.netty.SocketConnectionException: Channel set as inactive before valid response has been received
	at org.mockserver.client.netty.HttpClientConnectionHandler.updatePromise(HttpClientConnectionHandler.java:18)
	at org.mockserver.client.netty.HttpClientConnectionHandler.channelInactive(HttpClientConnectionHandler.java:24)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1409)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:927)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

[INFO]
[ERROR] Tests run: 1460, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] MockServer 5.3.1-SNAPSHOT .......................... SUCCESS [  2.313 s]
[INFO] MockServer Core .................................... FAILURE [ 17.081 s]
[INFO] MockServer Java Client ............................. SKIPPED
[INFO] MockServer Integration Test ........................ SKIPPED
[INFO] MockServer & Proxy Netty ........................... SKIPPED
[INFO] MockServer Web Archive ............................. SKIPPED
[INFO] MockServer Proxy Web Archive ....................... SKIPPED
[INFO] MockServer Examples 5.3.1-SNAPSHOT ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.600 s
[INFO] Finished at: 2018-06-13T19:36:05+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project mockserver-core: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/admin/Desktop/Mock-Server-Demo/mockservice/mockserver-core/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :mockserver-core

**Comment by PrashantMahajan-26** [comment]
We recently upgraded from Mock Server 3.10.2 to 5.3.0 and thereafter started hitting this issue in the tests.
Tried using the **withSecure(true)**  parameter but no luck.

Does the other solution mentioned will do the trick ?
`proxy_set_header Connection "keep-alive"; 
proxy_http_version 1.1; `

Please guide.

**Below is the snippet of Error :**

`Exception while sending request - java.lang.RuntimeException: Channel set as inactive before valid response has been received

TestName: oracle.sysman.emaas.test.CloudMonUIAddAccount.setUp, Status: FAIL, Completed: 2018-07-12 14:03:56.477 +0000

java.lang.RuntimeException: Exception while sending request - java.lang.RuntimeException: Channel set as inactive before valid response has been received

	at org.mockserver.client.netty.NettyHttpClient.sendRequest(NettyHttpClient.java:101)

	at org.mockserver.client.netty.NettyHttpClient.sendRequest(NettyHttpClient.java:33)

	at org.mockserver.client.AbstractClient.sendRequest(AbstractClient.java:89)

	at org.mockserver.client.AbstractClient.sendExpectation(AbstractClient.java:441)

	at org.mockserver.client.ForwardChainExpectation.callback(ForwardChainExpectation.java:50)

	at oracle.sysman.emaas.mockserver.MockRestService.startBasicAuth(MockRestService.java:319)

	at oracle.sysman.emaas.test.CloudMonSimulatorMgmt.runsimulator(CloudMonSimulatorMgmt.java:104)

	at oracle.sysman.emaas.test.CloudMonUIAddAccount.setUp(CloudMonUIAddAccount.java:124)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)

	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)

	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)

	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)

	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)

	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)

	at org.testng.TestRunner.privateRun(TestRunner.java:767)

	at org.testng.TestRunner.run(TestRunner.java:617)

	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)

	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)

	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)

	at org.testng.SuiteRunner.run(SuiteRunner.java:254)

	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)

	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)

	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)

	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)

	at org.testng.TestNG.run(TestNG.java:1057)

	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:112)

	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:57)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)

	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)

	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)

	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)

	at com.sun.proxy.$Proxy2.stop(Unknown Source)

	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:115)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)

	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)

	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)

	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Channel set as inactive before valid response has been received

	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)

	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:272)

	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)

	at org.mockserver.client.netty.NettyHttpClient.sendRequest(NettyHttpClient.java:80)

	... 51 more

Caused by: java.lang.RuntimeException: Channel set as inactive before valid response has been received

	at org.mockserver.client.netty.HttpClientConnectionHandler.updatePromise(HttpClientConnectionHandler.java:19)

	at org.mockserver.client.netty.HttpClientConnectionHandler.channelInactive(HttpClientConnectionHandler.java:25)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)

	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)

	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917)

	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)

	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)

	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)

	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)

	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)

	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)

	... 1 more`
