### ISSUE TITLE
Can we use Mock Server to bind to ports < 1024 ? I want it to listen to 443. (https).

### ISSUE THREAD

**Issue by mkarthick19** [jamesdbloom/mockserver#499]
By default, Mock Server doesn't allow us to bind to 443 port. Is there any workaround to this?
Please let me know.

**Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:443 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.5.jar:4.5.5]
	at com.vmware.evo.sddc.common.util.HttpClientService.getHTTPResponse(HttpClientService.java:538) ~[util-2.7.0-SNAPSHOT.jar:na]
	at com.vmware.evo.sddc.common.util.HttpClientService.getHTTPResponseAsString(HttpClientService.java:304) ~[util-2.7.0-SNAPSHOT.jar:na]
	at com.vmware.evo.sddc.common.util.HttpClientService.get(HttpClientService.java:178) ~[util-2.7.0-SNAPSHOT.jar:na]**

**Comment by Vampire** [comment]
Mock server doesn't restrict this.
I guess you are on Linux.
There the OS by default prevents binding to ports up to 1024 for non-root processes.
So you either have to run as `root` or lift this restriction on your OS or for the process like for example described at https://superuser.com/questions/710253/allow-non-root-process-to-bind-to-port-80-and-443.

**Comment by jamesdbloom** [comment]
@Vampire is completely correct so I am going to close this ticket
