### ISSUE TITLE
Unknown CA error under Windows

### ISSUE THREAD

**Issue by joemkeen** [jamesdbloom/mockserver#536]
Everything works great when mocking http requests, however once I switch over to https I am see the following:

io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: unknown_ca
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392) ~[mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:359) ~[mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342) ~[mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1010) ~[mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1409) [mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:927) [mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822) [mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_181]
Caused by: javax.net.ssl.SSLException: Received fatal alert: unknown_ca
        at sun.security.ssl.Alerts.getSSLException(Unknown Source) ~[na:1.8.0_181]
        at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source) ~[na:1.8.0_181]
        at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source) ~[na:1.8.0_181]
        at sun.security.ssl.SSLEngineImpl.recvAlert(Unknown Source) ~[na:1.8.0_181]
        at sun.security.ssl.SSLEngineImpl.readRecord(Unknown Source) ~[na:1.8.0_181]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(Unknown Source) ~[na:1.8.0_181]
        at sun.security.ssl.SSLEngineImpl.unwrap(Unknown Source) ~[na:1.8.0_181]
        at javax.net.ssl.SSLEngine.unwrap(Unknown Source) ~[na:1.8.0_181]
        at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:292) ~[mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1256) ~[mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1159) ~[mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1202) ~[mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[mockserver-netty-5.4.1-jar-with-dependencies.jar:na]
        ... 18 common frames omitted
2018-09-27 17:46:02,227 TRACE o.m.u.PortUnificationHandler [id: 0x2e46456f, L:/0:0:0:0:0:0:0:1:9999 ! R:/0:0:0:0:0:0:0:1:12532] UNREGISTERED
channel: 2e46456f
pipeline: [SslHandler#0, LoggingHandler#0, MockServerUnificationInitializer#0, DefaultChannelPipeline$TailContext#0]

Using MockServer via mockserver-netty-5.4.1-jar-with-dependencies.jar
Window 10
JRE 1.8.0_181

Installed CA certificate using the same process as described in the install_ca_certificate.sh script
Starting mockserver with: java -Djavax.net.ssl.trustStore="C:\Program Files\Java\jre1.8.0_181\lib\security\cacerts" -Dmockserver.logLevel=TRACE -classpath . -jar mockserver-netty-5.4.1-jar-with-dependencies.jar -serverPort 9999 -proxyRemotePort 9090 -proxyRemoteHost localhost

**Comment by jamesdbloom** [comment]
The cause of this issue is because the CA certificate has either not been installed in Windows or the CA certificate has not been setup as a trusted certificate correctly.  This is not an issue related to MockServer.  Unfortunately I do not currently have instructions on how to install CA certificates in Windows.  You could try following the instructions at: http://www.sqlservermart.com/HowTo/Windows_Import_Certificate.aspx
