### ISSUE TITLE
Autodetect WS or WSS for dashboard depending on HTTP or HTTPS

### ISSUE THREAD

**Issue by a459787545** [jamesdbloom/mockserver#584]
大神，您好！
请问将来会支持swagger设计的api导入吗，还有会提供一个可视化的界面来预览和调用mockserver的接口吗？

**Comment by jamesdbloom** [comment]
Can you please raise issues in english so that I can understand what you are requesting.

**Comment by a459787545** [comment]
Can you do a background page to configure? This makes it more efficient and easier to manage in actual work.thank you

**Comment by a459787545** [comment]
Can you provide a background management function, so that the work is most convenient?

**Comment by jamesdbloom** [comment]
I'm not sure what you mean by a background management function.  What do you want to manage?  The MockServer has a separate set of APIs to manage expectations that require sending `PUT` requests.

**Comment by jamesdbloom** [comment]
Yes there is a dashboard you can launch it from **/mockserver/dashboard** for example if MockServer is running on port 1080 then https://localhost:1080/mockserver/dashboard

This is not documented yet as the UI is fairly new, documentation will follow in the next few months.

**Comment by a459787545** [comment]
Hello, how can I solve this error?
<img width="1423" alt="2019-01-20 11 45 42" src="https://user-images.githubusercontent.com/16471580/51435057-3cb4a300-1caa-11e9-8652-c35415fe4d72.png">

**Comment by a459787545** [comment]
When I access the address "http://192.168.0.110:1080/mockserver/dashboard", I get an error :WebSocket connection to 'wss://192.168.0.110:1080/_mockserver_ui_websocket' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID.
<img width="1680" alt="2019-01-20 4 57 03" src="https://user-images.githubusercontent.com/16471580/51437517-5d94ec80-1cda-11e9-9806-3a9a8ce9a537.png">

**Comment by jamesdbloom** [comment]
Yes that makes sense because unfortunately currently the code assumes you are running the UI over TSL so the WebSocket is created over TSL (i.e. WSS).

If you can add the MockServer certificate to you OS and use HTTPS to load the dashboard then it will work, I will re-open this issue and rename the title to fix the dashboard so it auto detects whether is it running over TLS or not.

**Comment by a459787545** [comment]
Thank you. You've been a great help already.

**Comment by lifeisyours** [comment]
> 大神，您好！
> 请问将来会支持swagger设计的api导入吗，还有会提供一个可视化的界面来预览和调用mockserver的接口吗？

Hello, there!
Will there be future support for swagger designed API imports? Will there be a visual interface to preview and call mockserver's interface?

**Comment by jamesdbloom** [comment]
Yes both of these are on the roadmap and should be available within the next 6 months, first I need to resolve some other user requests and minor bugs and upgrade to Java 8 so that I can use existing swagger libraries.

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/Q7DowM6f/30-autodetect-ws-or-wss-for-dashboard-depending-on-http-or-https

**Comment by jamesdbloom** [comment]
this is now fixed and is in the SNAPSHOT release, this will be available in the next release in the next few weeks.

**Comment by sajli-31** [comment]
I feel like this issue is still persisting.

**Comment by bronumski** [comment]
> I feel like this issue is still persisting.

I am getting this error when running in a docker container over http

```
2023-11-30 20:46:53 5.15.0 SEVERE 80 web socket server caught exception 
2023-11-30T20:46:53.139911965Z io.netty.handler.codec.http.websocketx.WebSocketServerHandshakeException: not a WebSocket request: a |Connection| header must includes a token 'Upgrade'
2023-11-30T20:46:53.203855671Z 	at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker13.newHandshakeResponse(WebSocketServerHandshaker13.java:140)
2023-11-30T20:46:53.319486265Z 	at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker.handshake(WebSocketServerHandshaker.java:202)
2023-11-30T20:46:53.427558354Z 	at org.mockserver.dashboard.DashboardWebSocketHandler.upgradeChannel(DashboardWebSocketHandler.java:170)
2023-11-30T20:46:53.527492612Z 	at org.mockserver.dashboard.DashboardWebSocketHandler.channelRead(DashboardWebSocketHandler.java:129)
2023-11-30T20:46:53.588465124Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-11-30T20:46:53.765850549Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-11-30T20:46:53.766198012Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-11-30T20:46:53.766435361Z 	at org.mockserver.netty.websocketregistry.CallbackWebSocketServerHandler.channelRead(CallbackWebSocketServerHandler.java:57)
2023-11-30T20:46:53.766763739Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-11-30T20:46:53.767051849Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-11-30T20:46:53.767380488Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-11-30T20:46:53.767688251Z 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
2023-11-30T20:46:53.769912245Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-11-30T20:46:53.770776435Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-11-30T20:46:53.772109569Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-11-30T20:46:53.772474419Z 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
2023-11-30T20:46:53.772796464Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-11-30T20:46:53.775607940Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-11-30T20:46:53.887518198Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-11-30T20:46:53.993673310Z 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
2023-11-30T20:46:53.994740155Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-11-30T20:46:53.995186964Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-11-30T20:46:53.995782741Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-11-30T20:46:53.996166030Z 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
2023-11-30T20:46:53.997298316Z 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
2023-11-30T20:46:53.999543608Z 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
2023-11-30T20:46:54.005879889Z 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
2023-11-30T20:46:54.006572611Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
2023-11-30T20:46:54.006942951Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-11-30T20:46:54.007168261Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-11-30T20:46:54.007449348Z 	at org.mockserver.netty.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:335)
2023-11-30T20:46:54.007809983Z 	at org.mockserver.netty.unification.PortUnificationHandler.decode(PortUnificationHandler.java:173)
2023-11-30T20:46:54.070849853Z 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
2023-11-30T20:46:54.117954450Z 	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
2023-11-30T20:46:54.166065003Z 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
2023-11-30T20:46:54.166412726Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-11-30T20:46:54.166702360Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-11-30T20:46:54.166955429Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-11-30T20:46:54.170986208Z 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2023-11-30T20:46:54.171283176Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
2023-11-30T20:46:54.171591145Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-11-30T20:46:54.172558660Z 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2023-11-30T20:46:54.173293815Z 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
2023-11-30T20:46:54.174381138Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
2023-11-30T20:46:54.175526997Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
2023-11-30T20:46:54.186567386Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
2023-11-30T20:46:54.203555433Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
2023-11-30T20:46:54.207413432Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2023-11-30T20:46:54.364293286Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-11-30T20:46:54.426993708Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-11-30T20:46:54.427287068Z 
```

**Comment by faramarzaf** [comment]
I have the same issue, I can't see any logs in the dashboard after upgrading the mock server to 5.15.0 
Is there any solution for HTTP?
