### ISSUE TITLE
Problem with replacing ClientAndProxy

### ISSUE THREAD

**Issue by szakal** [jamesdbloom/mockserver#596]
I have to upgrade mock-server version to the newest 5.5.1 version. Since class ClientAndProxy is no longer available I struggle with replacing it with ClientAndServer class.

I try to follow documentation and given examples. There is a BooksPageIntegrationTest which demonstrates proxy usage I am interested in. I downloaded your sources and older implementations of that test based on ClientAndProxy worked fine (tests passed). However, when I switch to 5.5.1 tag the tests don't pass and I got the behavior exactly the same as my implementation. 

Here is the log from running BooksPageApacheClientIntegrationTest:
<pre>
16:15:32.452 [main] INFO  org.mockserver.mock.HttpStateHandler - started on port: 61688
16:15:32.460 [nioEventLoopGroup-4-4] INFO  org.mockserver.mock.HttpStateHandler - resetting all expectations and request logs
16:15:32.493 [nioEventLoopGroup-10-1] INFO  org.mockserver.mock.HttpStateHandler - creating expectation:

	{
	  "httpRequest" : {
	    "path" : "/get_book",
	    "queryStringParameters" : {
	      "id" : [ "1" ]
	    }
	  },
	  "times" : {
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponse" : {
	    "headers" : {
	      "content-type" : [ "application/json" ]
	    },
	    "body" : "{\n    \"id\": \"1\",\n    \"title\": \"Xenophon's imperial fiction : on the education of Cyrus\",\n    \"author\": \"James Tatum\",\n    \"isbn\": \"0691067570\",\n    \"publicationDate\": \"1989\"\n}"
	  }
	}

16:15:32.506 [nioEventLoopGroup-4-2] INFO  org.mockserver.mock.HttpStateHandler - no active expectations
16:15:32.516 [nioEventLoopGroup-10-2] INFO  org.mockserver.mock.HttpStateHandler - request:

	{
	  "method" : "GET",
	  "path" : "/get_book",
	  "queryStringParameters" : {
	    "id" : [ "1" ]
	  },
	  "headers" : {
	    "User-Agent" : [ "Apache-HttpClient/4.4.1 (Java/1.8.0_202)" ],
	    "x-forwarded-by" : [ "MockServer" ],
	    "host" : [ "localhost:61688" ],
	    "accept-encoding" : [ "gzip,deflate" ],
	    "content-length" : [ "0" ],
	    "connection" : [ "keep-alive" ]
	  },
	  "keepAlive" : true,
	  "secure" : false
	}

 matched expectation:

	{
	  "httpRequest" : {
	    "path" : "/get_book",
	    "queryStringParameters" : {
	      "id" : [ "1" ]
	    }
	  },
	  "times" : {
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponse" : {
	    "headers" : {
	      "content-type" : [ "application/json" ]
	    },
	    "body" : "{\n    \"id\": \"1\",\n    \"title\": \"Xenophon's imperial fiction : on the education of Cyrus\",\n    \"author\": \"James Tatum\",\n    \"isbn\": \"0691067570\",\n    \"publicationDate\": \"1989\"\n}"
	  }
	}

16:15:32.518 [pool-2-thread-9] INFO  org.mockserver.mock.HttpStateHandler - no expectation for:

	{
	  "method" : "GET",
	  "path" : "/get_book",
	  "queryStringParameters" : {
	    "id" : [ "1" ]
	  },
	  "headers" : {
	    "Host" : [ "localhost:61688" ],
	    "Proxy-Connection" : [ "Keep-Alive" ],
	    "User-Agent" : [ "Apache-HttpClient/4.4.1 (Java/1.8.0_202)" ],
	    "Accept-Encoding" : [ "gzip,deflate" ],
	    "content-length" : [ "0" ]
	  },
	  "keepAlive" : true,
	  "secure" : false
	}

 returning response:

	{
	  "statusCode" : 404,
	  "reasonPhrase" : "Not Found"
	}

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.RuntimeException: Exception making request to retrieve a book with id [1]

	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:160)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:127)
	at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:151)
	at org.mockserver.examples.proxy.web.controller.BooksPageIntegrationTest.shouldLoadSingleBook(BooksPageIntegrationTest.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.RuntimeException: Exception making request to retrieve a book with id [1]
	at org.mockserver.examples.proxy.service.apacheclient.BookServiceApacheHttpClient.getBook(BookServiceApacheHttpClient.java:83)
	at org.mockserver.examples.proxy.web.controller.BooksPageController.getBook(BooksPageController.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	... 41 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4145)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3091)
	at org.mockserver.examples.proxy.service.apacheclient.BookServiceApacheHttpClient.getBook(BookServiceApacheHttpClient.java:81)
	... 55 more

</pre>

I got exactly the same error (404) when I run my code. Could please confirm that this tests don't pass and propose some soution for that issue?

**Comment by jamesdbloom** [comment]
I have now updated the examples as some of the tests are marked with @Ignore for an unknown reason.  All the tests now pass and work correctly so please look at the example code again so you can copy that.  I have also updated the examples to the latest versions of those libraries on the assumption these are most commonly used.

Given the examples are now all correct and fully part of the CI pipeline I'm going to close this issue.  If you still have problems please add more comments here or open a new issue.
