### ISSUE TITLE
[>5.5.x] IllegalStateException while ask for "is mockserver running"

### ISSUE THREAD

**Issue by Fival85** [jamesdbloom/mockserver#626]
Hello,

we use the newest version of the Mockserver 5.5.4 at it seems to have a bug:

When you use following code snippet, the exception occurs. 
```
	import org.mockserver.configuration.ConfigurationProperties;
	import org.mockserver.integration.ClientAndServer;

	@Test
	public void testBuggyMockServer() {
		mockServer =  ClientAndServer.startClientAndServer(9123);
		mockServer.stop();
		mockServer.isRunning(10, 10000, TimeUnit.MILLISECONDS);
	}
```

the Exception:
```

java.lang.IllegalStateException: Request sent after client has been stopped - the event loop has been shutdown so it is not possible to send a request

	at org.mockserver.client.NettyHttpClient.sendRequest(NettyHttpClient.java:81)
	at org.mockserver.client.NettyHttpClient.sendRequest(NettyHttpClient.java:43)
	at org.mockserver.client.NettyHttpClient.sendRequest(NettyHttpClient.java:39)
	at org.mockserver.client.NettyHttpClient.sendRequest(NettyHttpClient.java:87)
	at org.mockserver.client.MockServerClient.sendRequest(MockServerClient.java:158)
	at org.mockserver.client.MockServerClient.isRunning(MockServerClient.java:200)
	at MockServerBugTest.testBuggyMockServer(MockServerBugTest.java:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


```

I think "isRunning" should not throw such an exception

greetz
Dennis

**Comment by jamesdbloom** [comment]
The main issue is that this is more complex than would appear at face value.  When the client is stopped it can't actually query the server to accurately determine if it is running.  However, it is a good assumption that if the client is stopped the server is likely stopped because typically the client is only stopped when it is used to request the server to stop.  I'm going to use this assumption to remove this exception because typically it is correct and there is no technical to guarantee the state.
