### ISSUE TITLE
Error starting mock server - java.lang.NoSuchFieldError: WRITE_BUFFER_WATER_MARK

### ISSUE THREAD

**Issue by Galileo1** [jamesdbloom/mockserver#652]
I am getting the following error while starting the mock server from java api 
`mockServer = startClientAndServer(1080);`

> Stacktrace

```
java.lang.NoSuchFieldError: WRITE_BUFFER_WATER_MARK

	at org.mockserver.mockserver.MockServer.<init>(MockServer.java:35)
	at org.mockserver.integration.ClientAndServer.<init>(ClientAndServer.java:20)
	at org.mockserver.integration.ClientAndServer.startClientAndServer(ClientAndServer.java:29)
	at com.varun.BrowserProxyTest.setUp(BrowserProxyTest.java:45)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by ChandanNM** [comment]
I am seeing this as well, no matter what version of mockserver I switch to

**Comment by ChandanNM** [comment]
Below is the stacktrace with 5.6.0 version :

`FAILED: init
java.lang.NoSuchFieldError: WRITE_BUFFER_WATER_MARK
	at org.mockserver.mockserver.MockServer.createServerBootstrap(MockServer.java:93)
	at org.mockserver.mockserver.MockServer.<init>(MockServer.java:45)
	at org.mockserver.mockserver.MockServer.<init>(MockServer.java:35)
	at org.mockserver.integration.ClientAndServer.<init>(ClientAndServer.java:19)
	at org.mockserver.integration.ClientAndServer.startClientAndServer(ClientAndServer.java:30)
	at com.cisco.collab.terminus.test.functional.v2.AuditCustomerV2Test.init(AuditCustomerV2Test.java:31)`

**Comment by ChandanNM** [comment]
Here is the code : 
`	private static final Logger LOG = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());

	private static final int DEFAULT_MOCK_SERVER_PORT = 1080;
	private static final String LOCALHOST = "localhost";

	private ClientAndServer mockServer;
	private MockServerClient mockClient;

	@Test
	public void init() throws IOException, URISyntaxException {

		mockServer = startClientAndServer(DEFAULT_MOCK_SERVER_PORT);
		LOG.info("Using existing mock container on host {}, port {}", LOCALHOST, DEFAULT_MOCK_SERVER_PORT);
		mockClient = new MockServerClient(LOCALHOST, DEFAULT_MOCK_SERVER_PORT);
		Assert.assertTrue(mockClient.isRunning(), "Mock client should be connected and running");
	}
`

**Comment by ChandanNM** [comment]
Here is the code - 
`	private static final Logger LOG = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());

	private static final int DEFAULT_MOCK_SERVER_PORT = 1080;
	private static final String LOCALHOST = "localhost";

	private ClientAndServer mockServer;
	private MockServerClient mockClient;

	@Test
	public void init() throws IOException, URISyntaxException {

		mockServer = startClientAndServer(DEFAULT_MOCK_SERVER_PORT);
		LOG.info("Starting mock server on host {}, port {}", LOCALHOST, DEFAULT_MOCK_SERVER_PORT);
		mockClient = new MockServerClient(LOCALHOST, DEFAULT_MOCK_SERVER_PORT);
		Assert.assertTrue(mockClient.isRunning(), "Mock client should be connected and running");
	}
`

**Comment by AngleZhou** [comment]
Same here. 
Just followed the [manual](http://www.mock-server.com/mock_server/getting_started.html):
1. Add plugin dependency and mockserver-netty dependency in pom.xml
2. Started server with  `mockServer = startClientAndServer(1080);` in my unit test.

**Comment by AngleZhou** [comment]
The cause should be that our project is using an old version of netty: 4.1.0.CR3. 
![Screen Shot 2019-08-07 at 11 11 52 AM](https://user-images.githubusercontent.com/10024128/62592037-39120200-b904-11e9-9971-a4c8ac478f3e.png)
However, these two fields have been deprecated. [Ref
](https://stackoverflow.com/questions/25281124/netty-4-high-and-low-write-watermarks)

An older version should solve the problem.

**Comment by AngleZhou** [comment]
@jamesdbloom 
Does this mean the netty version update is included in almost every release?  And the only way I can use mockServer is to update netty?
<img width="1015" alt="Screen Shot 2019-08-07 at 11 32 32 AM" src="https://user-images.githubusercontent.com/10024128/62592824-2816c000-b907-11e9-8387-c99bc2f52236.png">

**Comment by jamesdbloom** [comment]
Yes, unfortunately, it does mean that.  The other option is to use run the Mock Server in a separate JVM for example by using the docker container or maven plugin.

I would like to resolve this issue in a more gracefully way but realistically the only way to resolve this issue is to either use an updated version of Netty or run the Mock Server in a separate JVM for example by using the docker container, maven plugin or node module.

**Comment by jamesdbloom** [comment]
This code change was made in Netty 4 years ago and unfortunately, it is not practical for MockServer to depend on such an old version of Netty particularly as a number of bugs in Netty have been fixed since then resolving bugs in MockServer.
