### ISSUE TITLE
java.lang.NullPointerException after upgrading to 5.7.1

### ISSUE THREAD

**Issue by flozano** [jamesdbloom/mockserver#688]
```
[2019-11-15T07:19:13.946Z] [ERROR] [MockServer-EventLog0] org.mockserver.log.MockServerEventLog Exception handling log entry in log ring buffer, for log entry: {
  "logLevel" : "INFO",
  "timestamp" : "2019-11-15 08:19:13",
  "type" : "RUNNABLE"
} java.lang.NullPointerException: null
	at java.base/java.util.Arrays.stream(Arrays.java:5614)
	at org.mockserver.log.MockServerEventLog.lambda$null$18(MockServerEventLog.java:280)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue$CLQSpliterator.forEachRemaining(ConcurrentLinkedQueue.java:894)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.mockserver.log.MockServerEventLog.lambda$retrieveRequests$11(MockServerEventLog.java:217)
	at org.mockserver.log.MockServerEventLog.lambda$retrieveLogEntries$19(MockServerEventLog.java:277)
	at org.mockserver.log.MockServerEventLog.lambda$startRingBuffer$5(MockServerEventLog.java:122)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

The code to trigger it is a little project-specific, but it's more or less like this:
```java
		MyResponse response = new MyResponse();
		HttpRequest mockRequest = mockRequest(myPath(), "POST", contentType(MULTIPART_MEDIA_TYPE),
				accept(MyResponse.JSON_MIME_TYPE));
		mockServer.when(mockRequest)
				.respond(mockResponse(response, contentType(MyResponse.JSON_MIME_TYPE), 200));
		MyResponse result = myClient.doSomething("a", "b", "c").join();
```
mockResponse method is a utility method (that should not be there IMHO) but does more or less this:
```java
	protected static <T> HttpResponse mockResponse(T body, Header contentType, int statusCode) throws Exception {
		HttpResponse response = new HttpResponse();

		if (contentType != null)
			response.withHeaders(contentType);

		if (body != null) {
			if (body instanceof String) {
				response.withBody(body.toString());
			} else if (body instanceof byte[]) {
				response.withBody((byte[]) body);
			} else if (body instanceof InputStream) {
				response.withBody(IOUtils.toByteArray((InputStream) body));
			} else {
				response.withBody(mapper.writeValueAsString(body));
			}
		}

		return response.withStatusCode(statusCode);
	}
```

**Comment by flozano** [comment]
`                        .stream(logItem.getHttpRequests())`
in
```java
    private <T> void retrieveLogEntries(HttpRequest httpRequest, Predicate<LogEntry> logEntryPredicate, Function<LogEntry, T> logEntryMapper, Consumer<Stream<T>> consumer) {
        disruptor.publishEvent(new LogEntry()
            .setType(RUNNABLE)
            .setConsumer(() -> {
                HttpRequestMatcher httpRequestMatcher = matcherBuilder.transformsToMatcher(httpRequest);
                consumer.accept(this.requestLog
                    .stream()
                    .filter(logItem -> Arrays
                        .stream(logItem.getHttpRequests())
                        .anyMatch(httpRequestMatcher::matches)
                    )
                    .filter(logEntryPredicate)
                    .map(logEntryMapper)
                );
            })
        );
    }
```
it seems `getHttpRequests()` returns null.

**Comment by flozano** [comment]
Confirmed that downgrading to 5.6.1 fixes the issue

**Comment by jamesdbloom** [comment]
I’ll fix this. There will be a new release in the next few days with this fix and some other minor improvements.

**Comment by jamesdbloom** [comment]
This is now fixed in the SNAPSHOT version and will be released in the next few days.
