### ISSUE TITLE
Exceptions loop

### ISSUE THREAD

**Issue by IGZrobertogonzalez** [jamesdbloom/mockserver#96]
Hi James,

when I run tests with ServerMock (via @Rule or programmatically) I get exceptions loop. I use Intellij 14 to run junit tests. Any idea? Thank you.
```
2015-02-18 13:42:53,352 WARN i.n.c.DefaultChannelPipeline An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.ClassCastException: io.netty.util.ThreadDeathWatcher$Entry cannot be cast to java.lang.Runnable
	at io.netty.util.internal.MpscLinkedQueue.add(MpscLinkedQueue.java:41) ~[netty-all-4.0.19.Final.jar:4.0.19.Final]
	at io.netty.util.ThreadDeathWatcher.schedule(ThreadDeathWatcher.java:88) ~[netty-common-4.0.24.Final.jar:4.0.19.Final]
	at io.netty.util.ThreadDeathWatcher.watch(ThreadDeathWatcher.java:70) ~[netty-common-4.0.24.Final.jar:4.0.19.Final]
	at io.netty.buffer.PoolThreadCache.<init>(PoolThreadCache.java:111) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:305) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:284) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.util.concurrent.FastThreadLocal.initialize(FastThreadLocal.java:155) ~[netty-common-4.0.24.Final.jar:4.0.19.Final]
	at io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:149) ~[netty-common-4.0.24.Final.jar:4.0.19.Final]
	at io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:135) ~[netty-common-4.0.24.Final.jar:4.0.19.Final]
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:245) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:146) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:107) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.channel.AdaptiveRecvByteBufAllocator$HandleImpl.allocate(AdaptiveRecvByteBufAllocator.java:104) ~[netty-transport-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117) ~[netty-transport-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.19.Final.jar:4.0.19.Final]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
2015-02-18 13:42:53,374 WARN i.n.c.DefaultChannelPipeline An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.ClassCastException: io.netty.util.ThreadDeathWatcher$Entry cannot be cast to java.lang.Runnable
	at io.netty.util.internal.MpscLinkedQueue.add(MpscLinkedQueue.java:41) ~[netty-all-4.0.19.Final.jar:4.0.19.Final]
	at io.netty.util.ThreadDeathWatcher.schedule(ThreadDeathWatcher.java:88) ~[netty-common-4.0.24.Final.jar:4.0.19.Final]
	at io.netty.util.ThreadDeathWatcher.watch(ThreadDeathWatcher.java:70) ~[netty-common-4.0.24.Final.jar:4.0.19.Final]
	at io.netty.buffer.PoolThreadCache.<init>(PoolThreadCache.java:111) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:305) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:284) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.util.concurrent.FastThreadLocal.initialize(FastThreadLocal.java:155) ~[netty-common-4.0.24.Final.jar:4.0.19.Final]
	at io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:149) ~[netty-common-4.0.24.Final.jar:4.0.19.Final]
	at io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:135) ~[netty-common-4.0.24.Final.jar:4.0.19.Final]
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:245) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:146) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:107) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.channel.AdaptiveRecvByteBufAllocator$HandleImpl.allocate(AdaptiveRecvByteBufAllocator.java:104) ~[netty-transport-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117) ~[netty-transport-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.19.Final.jar:4.0.19.Final]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
...
```

**Comment by IGZrobertogonzalez** [comment]
I found the problem!!

Maven dependencies priority. If you put:
```
<!--Mock server-->
        <dependency>
            <groupId>org.mock-server</groupId>
            <artifactId>mockserver-core</artifactId>
            <version>3.9.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mock-server</groupId>
            <artifactId>mockserver-client</artifactId>
            <version>3.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mock-server</groupId>
            <artifactId>mockserver-netty</artifactId>
            <version>3.9.1</version>
            <scope>test</scope>
        </dependency>
```
mockserver-core depends of netty 4.0.19 jars, but mockserver-netty depends of 4.0.24.

I changed the position et voila

**Comment by jamesdbloom** [comment]
That's very strange because they all use a super Pom which has a dependencyManagement section defining the versions globally.  I'll look into this and see what's going on.

**Comment by IGZrobertogonzalez** [comment]
Sorry, I see mockserver-client 3.2 depends of 4.0.19.Final. That jar add dependency of 4.0.19.Final.
If you change below dependency order, it fails:
```
<!--Mock server-->
        <dependency>
            <groupId>org.mock-server</groupId>
            <artifactId>mockserver-client</artifactId>
            <version>3.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mock-server</groupId>
            <artifactId>mockserver-core</artifactId>
            <version>3.9.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mock-server</groupId>
            <artifactId>mockserver-netty</artifactId>
            <version>3.9.1</version>
            <scope>test</scope>
        </dependency>
```
I hope help you

**Comment by jamesdbloom** [comment]
Is there a reason why do you have a different version of the mockserver-client? All the mock server dependencies should have the same version.  I'm pretty sure that is why you are having this problem.

You need to use version 3.9.1 or version 3.2 consistently for all org.mock-server dependencies.

**Comment by IGZrobertogonzalez** [comment]
When I start with a new technology I prefer to use the last version, but mockserver-client is in 3.2 according to maven cental http://mvnrepository.com/artifact/org.mock-server/mockserver-client
I think I can move to mockserver-client-java version 3.9.1

Thank you!

**Comment by jamesdbloom** [comment]
Yes sorry your correct mockserver-client is actually on old module the module got renamed to mockserver-client-java when the ruby and javascript clients were added.  There is no way to remove the old module from Maven Central that I'm aware of otherwise I would remove it.
